#define BOOST_TEST_DYN_LINK
#include <boost/test/unit_test.hpp>

#define MATH_CORE_SWIZZLE_ENABLE_ELEMENT_ACCESSORS
#include <math/types.hpp>

BOOST_AUTO_TEST_SUITE(Vector4_swizzles)

BOOST_AUTO_TEST_CASE(add) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(add_eq) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(sub) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(sub_eq) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(mult) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(mult_eq) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(div) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(div_eq) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(scalar_mult) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(scalar_mult_eq) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(scalar_div) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(scalar_div_eq) {
	// TODO
	BOOST_CHECK_MESSAGE(false, "test not implemented");
}

BOOST_AUTO_TEST_CASE(access) {
	math::Vector4 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	// 2d swizzles <x, y, z, w>
	auto xx = V.xx;
	BOOST_CHECK_CLOSE(xx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xx.getE2(), V.x, 1e-5f);
	auto xy = V.xy;
	BOOST_CHECK_CLOSE(xy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xy.getE2(), V.y, 1e-5f);
	auto xz = V.xz;
	BOOST_CHECK_CLOSE(xz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xz.getE2(), V.z, 1e-5f);
	auto xw = V.xw;
	BOOST_CHECK_CLOSE(xw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xw.getE2(), V.w, 1e-5f);
	auto yx = V.yx;
	BOOST_CHECK_CLOSE(yx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yx.getE2(), V.x, 1e-5f);
	auto yy = V.yy;
	BOOST_CHECK_CLOSE(yy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yy.getE2(), V.y, 1e-5f);
	auto yz = V.yz;
	BOOST_CHECK_CLOSE(yz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yz.getE2(), V.z, 1e-5f);
	auto yw = V.yw;
	BOOST_CHECK_CLOSE(yw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yw.getE2(), V.w, 1e-5f);
	auto zx = V.zx;
	BOOST_CHECK_CLOSE(zx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zx.getE2(), V.x, 1e-5f);
	auto zy = V.zy;
	BOOST_CHECK_CLOSE(zy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zy.getE2(), V.y, 1e-5f);
	auto zz = V.zz;
	BOOST_CHECK_CLOSE(zz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zz.getE2(), V.z, 1e-5f);
	auto zw = V.zw;
	BOOST_CHECK_CLOSE(zw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zw.getE2(), V.w, 1e-5f);
	auto wx = V.wx;
	BOOST_CHECK_CLOSE(wx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wx.getE2(), V.x, 1e-5f);
	auto wy = V.wy;
	BOOST_CHECK_CLOSE(wy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wy.getE2(), V.y, 1e-5f);
	auto wz = V.wz;
	BOOST_CHECK_CLOSE(wz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wz.getE2(), V.z, 1e-5f);
	auto ww = V.ww;
	BOOST_CHECK_CLOSE(ww.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ww.getE2(), V.w, 1e-5f);
	// 3d swizzles <x, y, z, w>
	auto xxx = V.xxx;
	BOOST_CHECK_CLOSE(xxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxx.getE3(), V.x, 1e-5f);
	auto xxy = V.xxy;
	BOOST_CHECK_CLOSE(xxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxy.getE3(), V.y, 1e-5f);
	auto xxz = V.xxz;
	BOOST_CHECK_CLOSE(xxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxz.getE3(), V.z, 1e-5f);
	auto xxw = V.xxw;
	BOOST_CHECK_CLOSE(xxw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxw.getE3(), V.w, 1e-5f);
	auto xyx = V.xyx;
	BOOST_CHECK_CLOSE(xyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyx.getE3(), V.x, 1e-5f);
	auto xyy = V.xyy;
	BOOST_CHECK_CLOSE(xyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyy.getE3(), V.y, 1e-5f);
	auto xyz = V.xyz;
	BOOST_CHECK_CLOSE(xyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyz.getE3(), V.z, 1e-5f);
	auto xyw = V.xyw;
	BOOST_CHECK_CLOSE(xyw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyw.getE3(), V.w, 1e-5f);
	auto xzx = V.xzx;
	BOOST_CHECK_CLOSE(xzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzx.getE3(), V.x, 1e-5f);
	auto xzy = V.xzy;
	BOOST_CHECK_CLOSE(xzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzy.getE3(), V.y, 1e-5f);
	auto xzz = V.xzz;
	BOOST_CHECK_CLOSE(xzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzz.getE3(), V.z, 1e-5f);
	auto xzw = V.xzw;
	BOOST_CHECK_CLOSE(xzw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzw.getE3(), V.w, 1e-5f);
	auto xwx = V.xwx;
	BOOST_CHECK_CLOSE(xwx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwx.getE3(), V.x, 1e-5f);
	auto xwy = V.xwy;
	BOOST_CHECK_CLOSE(xwy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwy.getE3(), V.y, 1e-5f);
	auto xwz = V.xwz;
	BOOST_CHECK_CLOSE(xwz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwz.getE3(), V.z, 1e-5f);
	auto xww = V.xww;
	BOOST_CHECK_CLOSE(xww.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xww.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xww.getE3(), V.w, 1e-5f);
	auto yxx = V.yxx;
	BOOST_CHECK_CLOSE(yxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxx.getE3(), V.x, 1e-5f);
	auto yxy = V.yxy;
	BOOST_CHECK_CLOSE(yxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxy.getE3(), V.y, 1e-5f);
	auto yxz = V.yxz;
	BOOST_CHECK_CLOSE(yxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxz.getE3(), V.z, 1e-5f);
	auto yxw = V.yxw;
	BOOST_CHECK_CLOSE(yxw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxw.getE3(), V.w, 1e-5f);
	auto yyx = V.yyx;
	BOOST_CHECK_CLOSE(yyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyx.getE3(), V.x, 1e-5f);
	auto yyy = V.yyy;
	BOOST_CHECK_CLOSE(yyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyy.getE3(), V.y, 1e-5f);
	auto yyz = V.yyz;
	BOOST_CHECK_CLOSE(yyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyz.getE3(), V.z, 1e-5f);
	auto yyw = V.yyw;
	BOOST_CHECK_CLOSE(yyw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyw.getE3(), V.w, 1e-5f);
	auto yzx = V.yzx;
	BOOST_CHECK_CLOSE(yzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzx.getE3(), V.x, 1e-5f);
	auto yzy = V.yzy;
	BOOST_CHECK_CLOSE(yzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzy.getE3(), V.y, 1e-5f);
	auto yzz = V.yzz;
	BOOST_CHECK_CLOSE(yzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzz.getE3(), V.z, 1e-5f);
	auto yzw = V.yzw;
	BOOST_CHECK_CLOSE(yzw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzw.getE3(), V.w, 1e-5f);
	auto ywx = V.ywx;
	BOOST_CHECK_CLOSE(ywx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywx.getE3(), V.x, 1e-5f);
	auto ywy = V.ywy;
	BOOST_CHECK_CLOSE(ywy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywy.getE3(), V.y, 1e-5f);
	auto ywz = V.ywz;
	BOOST_CHECK_CLOSE(ywz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywz.getE3(), V.z, 1e-5f);
	auto yww = V.yww;
	BOOST_CHECK_CLOSE(yww.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yww.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yww.getE3(), V.w, 1e-5f);
	auto zxx = V.zxx;
	BOOST_CHECK_CLOSE(zxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxx.getE3(), V.x, 1e-5f);
	auto zxy = V.zxy;
	BOOST_CHECK_CLOSE(zxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxy.getE3(), V.y, 1e-5f);
	auto zxz = V.zxz;
	BOOST_CHECK_CLOSE(zxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxz.getE3(), V.z, 1e-5f);
	auto zxw = V.zxw;
	BOOST_CHECK_CLOSE(zxw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxw.getE3(), V.w, 1e-5f);
	auto zyx = V.zyx;
	BOOST_CHECK_CLOSE(zyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyx.getE3(), V.x, 1e-5f);
	auto zyy = V.zyy;
	BOOST_CHECK_CLOSE(zyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyy.getE3(), V.y, 1e-5f);
	auto zyz = V.zyz;
	BOOST_CHECK_CLOSE(zyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyz.getE3(), V.z, 1e-5f);
	auto zyw = V.zyw;
	BOOST_CHECK_CLOSE(zyw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyw.getE3(), V.w, 1e-5f);
	auto zzx = V.zzx;
	BOOST_CHECK_CLOSE(zzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzx.getE3(), V.x, 1e-5f);
	auto zzy = V.zzy;
	BOOST_CHECK_CLOSE(zzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzy.getE3(), V.y, 1e-5f);
	auto zzz = V.zzz;
	BOOST_CHECK_CLOSE(zzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzz.getE3(), V.z, 1e-5f);
	auto zzw = V.zzw;
	BOOST_CHECK_CLOSE(zzw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzw.getE3(), V.w, 1e-5f);
	auto zwx = V.zwx;
	BOOST_CHECK_CLOSE(zwx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwx.getE3(), V.x, 1e-5f);
	auto zwy = V.zwy;
	BOOST_CHECK_CLOSE(zwy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwy.getE3(), V.y, 1e-5f);
	auto zwz = V.zwz;
	BOOST_CHECK_CLOSE(zwz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwz.getE3(), V.z, 1e-5f);
	auto zww = V.zww;
	BOOST_CHECK_CLOSE(zww.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zww.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zww.getE3(), V.w, 1e-5f);
	auto wxx = V.wxx;
	BOOST_CHECK_CLOSE(wxx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxx.getE3(), V.x, 1e-5f);
	auto wxy = V.wxy;
	BOOST_CHECK_CLOSE(wxy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxy.getE3(), V.y, 1e-5f);
	auto wxz = V.wxz;
	BOOST_CHECK_CLOSE(wxz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxz.getE3(), V.z, 1e-5f);
	auto wxw = V.wxw;
	BOOST_CHECK_CLOSE(wxw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxw.getE3(), V.w, 1e-5f);
	auto wyx = V.wyx;
	BOOST_CHECK_CLOSE(wyx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyx.getE3(), V.x, 1e-5f);
	auto wyy = V.wyy;
	BOOST_CHECK_CLOSE(wyy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyy.getE3(), V.y, 1e-5f);
	auto wyz = V.wyz;
	BOOST_CHECK_CLOSE(wyz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyz.getE3(), V.z, 1e-5f);
	auto wyw = V.wyw;
	BOOST_CHECK_CLOSE(wyw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyw.getE3(), V.w, 1e-5f);
	auto wzx = V.wzx;
	BOOST_CHECK_CLOSE(wzx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzx.getE3(), V.x, 1e-5f);
	auto wzy = V.wzy;
	BOOST_CHECK_CLOSE(wzy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzy.getE3(), V.y, 1e-5f);
	auto wzz = V.wzz;
	BOOST_CHECK_CLOSE(wzz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzz.getE3(), V.z, 1e-5f);
	auto wzw = V.wzw;
	BOOST_CHECK_CLOSE(wzw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzw.getE3(), V.w, 1e-5f);
	auto wwx = V.wwx;
	BOOST_CHECK_CLOSE(wwx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwx.getE3(), V.x, 1e-5f);
	auto wwy = V.wwy;
	BOOST_CHECK_CLOSE(wwy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwy.getE3(), V.y, 1e-5f);
	auto wwz = V.wwz;
	BOOST_CHECK_CLOSE(wwz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwz.getE3(), V.z, 1e-5f);
	auto www = V.www;
	BOOST_CHECK_CLOSE(www.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(www.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(www.getE3(), V.w, 1e-5f);
	// 4d swizzles <x, y, z, w>
	auto xxxx = V.xxxx;
	BOOST_CHECK_CLOSE(xxxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxx.getE4(), V.x, 1e-5f);
	auto xxxy = V.xxxy;
	BOOST_CHECK_CLOSE(xxxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxy.getE4(), V.y, 1e-5f);
	auto xxxz = V.xxxz;
	BOOST_CHECK_CLOSE(xxxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxz.getE4(), V.z, 1e-5f);
	auto xxxw = V.xxxw;
	BOOST_CHECK_CLOSE(xxxw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxw.getE4(), V.w, 1e-5f);
	auto xxyx = V.xxyx;
	BOOST_CHECK_CLOSE(xxyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xxyx.getE4(), V.x, 1e-5f);
	auto xxyy = V.xxyy;
	BOOST_CHECK_CLOSE(xxyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xxyy.getE4(), V.y, 1e-5f);
	auto xxyz = V.xxyz;
	BOOST_CHECK_CLOSE(xxyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xxyz.getE4(), V.z, 1e-5f);
	auto xxyw = V.xxyw;
	BOOST_CHECK_CLOSE(xxyw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xxyw.getE4(), V.w, 1e-5f);
	auto xxzx = V.xxzx;
	BOOST_CHECK_CLOSE(xxzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xxzx.getE4(), V.x, 1e-5f);
	auto xxzy = V.xxzy;
	BOOST_CHECK_CLOSE(xxzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xxzy.getE4(), V.y, 1e-5f);
	auto xxzz = V.xxzz;
	BOOST_CHECK_CLOSE(xxzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xxzz.getE4(), V.z, 1e-5f);
	auto xxzw = V.xxzw;
	BOOST_CHECK_CLOSE(xxzw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xxzw.getE4(), V.w, 1e-5f);
	auto xxwx = V.xxwx;
	BOOST_CHECK_CLOSE(xxwx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxwx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xxwx.getE4(), V.x, 1e-5f);
	auto xxwy = V.xxwy;
	BOOST_CHECK_CLOSE(xxwy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxwy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xxwy.getE4(), V.y, 1e-5f);
	auto xxwz = V.xxwz;
	BOOST_CHECK_CLOSE(xxwz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxwz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xxwz.getE4(), V.z, 1e-5f);
	auto xxww = V.xxww;
	BOOST_CHECK_CLOSE(xxww.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxww.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xxww.getE4(), V.w, 1e-5f);
	auto xyxx = V.xyxx;
	BOOST_CHECK_CLOSE(xyxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxx.getE4(), V.x, 1e-5f);
	auto xyxy = V.xyxy;
	BOOST_CHECK_CLOSE(xyxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxy.getE4(), V.y, 1e-5f);
	auto xyxz = V.xyxz;
	BOOST_CHECK_CLOSE(xyxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxz.getE4(), V.z, 1e-5f);
	auto xyxw = V.xyxw;
	BOOST_CHECK_CLOSE(xyxw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxw.getE4(), V.w, 1e-5f);
	auto xyyx = V.xyyx;
	BOOST_CHECK_CLOSE(xyyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyx.getE4(), V.x, 1e-5f);
	auto xyyy = V.xyyy;
	BOOST_CHECK_CLOSE(xyyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyy.getE4(), V.y, 1e-5f);
	auto xyyz = V.xyyz;
	BOOST_CHECK_CLOSE(xyyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyz.getE4(), V.z, 1e-5f);
	auto xyyw = V.xyyw;
	BOOST_CHECK_CLOSE(xyyw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyyw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyw.getE4(), V.w, 1e-5f);
	auto xyzx = V.xyzx;
	BOOST_CHECK_CLOSE(xyzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyzx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xyzx.getE4(), V.x, 1e-5f);
	auto xyzy = V.xyzy;
	BOOST_CHECK_CLOSE(xyzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyzy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xyzy.getE4(), V.y, 1e-5f);
	auto xyzz = V.xyzz;
	BOOST_CHECK_CLOSE(xyzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyzz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xyzz.getE4(), V.z, 1e-5f);
	auto xyzw = V.xyzw;
	BOOST_CHECK_CLOSE(xyzw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyzw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xyzw.getE4(), V.w, 1e-5f);
	auto xywx = V.xywx;
	BOOST_CHECK_CLOSE(xywx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xywx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xywx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xywx.getE4(), V.x, 1e-5f);
	auto xywy = V.xywy;
	BOOST_CHECK_CLOSE(xywy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xywy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xywy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xywy.getE4(), V.y, 1e-5f);
	auto xywz = V.xywz;
	BOOST_CHECK_CLOSE(xywz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xywz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xywz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xywz.getE4(), V.z, 1e-5f);
	auto xyww = V.xyww;
	BOOST_CHECK_CLOSE(xyww.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyww.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xyww.getE4(), V.w, 1e-5f);
	auto xzxx = V.xzxx;
	BOOST_CHECK_CLOSE(xzxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxx.getE4(), V.x, 1e-5f);
	auto xzxy = V.xzxy;
	BOOST_CHECK_CLOSE(xzxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxy.getE4(), V.y, 1e-5f);
	auto xzxz = V.xzxz;
	BOOST_CHECK_CLOSE(xzxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxz.getE4(), V.z, 1e-5f);
	auto xzxw = V.xzxw;
	BOOST_CHECK_CLOSE(xzxw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxw.getE4(), V.w, 1e-5f);
	auto xzyx = V.xzyx;
	BOOST_CHECK_CLOSE(xzyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzyx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xzyx.getE4(), V.x, 1e-5f);
	auto xzyy = V.xzyy;
	BOOST_CHECK_CLOSE(xzyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzyy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xzyy.getE4(), V.y, 1e-5f);
	auto xzyz = V.xzyz;
	BOOST_CHECK_CLOSE(xzyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzyz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xzyz.getE4(), V.z, 1e-5f);
	auto xzyw = V.xzyw;
	BOOST_CHECK_CLOSE(xzyw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzyw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xzyw.getE4(), V.w, 1e-5f);
	auto xzzx = V.xzzx;
	BOOST_CHECK_CLOSE(xzzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzx.getE4(), V.x, 1e-5f);
	auto xzzy = V.xzzy;
	BOOST_CHECK_CLOSE(xzzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzy.getE4(), V.y, 1e-5f);
	auto xzzz = V.xzzz;
	BOOST_CHECK_CLOSE(xzzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzz.getE4(), V.z, 1e-5f);
	auto xzzw = V.xzzw;
	BOOST_CHECK_CLOSE(xzzw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzzw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzw.getE4(), V.w, 1e-5f);
	auto xzwx = V.xzwx;
	BOOST_CHECK_CLOSE(xzwx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzwx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xzwx.getE4(), V.x, 1e-5f);
	auto xzwy = V.xzwy;
	BOOST_CHECK_CLOSE(xzwy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzwy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xzwy.getE4(), V.y, 1e-5f);
	auto xzwz = V.xzwz;
	BOOST_CHECK_CLOSE(xzwz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzwz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xzwz.getE4(), V.z, 1e-5f);
	auto xzww = V.xzww;
	BOOST_CHECK_CLOSE(xzww.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzww.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xzww.getE4(), V.w, 1e-5f);
	auto xwxx = V.xwxx;
	BOOST_CHECK_CLOSE(xwxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwxx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwxx.getE4(), V.x, 1e-5f);
	auto xwxy = V.xwxy;
	BOOST_CHECK_CLOSE(xwxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwxy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwxy.getE4(), V.y, 1e-5f);
	auto xwxz = V.xwxz;
	BOOST_CHECK_CLOSE(xwxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwxz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwxz.getE4(), V.z, 1e-5f);
	auto xwxw = V.xwxw;
	BOOST_CHECK_CLOSE(xwxw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwxw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwxw.getE4(), V.w, 1e-5f);
	auto xwyx = V.xwyx;
	BOOST_CHECK_CLOSE(xwyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwyx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xwyx.getE4(), V.x, 1e-5f);
	auto xwyy = V.xwyy;
	BOOST_CHECK_CLOSE(xwyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwyy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xwyy.getE4(), V.y, 1e-5f);
	auto xwyz = V.xwyz;
	BOOST_CHECK_CLOSE(xwyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwyz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xwyz.getE4(), V.z, 1e-5f);
	auto xwyw = V.xwyw;
	BOOST_CHECK_CLOSE(xwyw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwyw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xwyw.getE4(), V.w, 1e-5f);
	auto xwzx = V.xwzx;
	BOOST_CHECK_CLOSE(xwzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwzx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xwzx.getE4(), V.x, 1e-5f);
	auto xwzy = V.xwzy;
	BOOST_CHECK_CLOSE(xwzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwzy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xwzy.getE4(), V.y, 1e-5f);
	auto xwzz = V.xwzz;
	BOOST_CHECK_CLOSE(xwzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwzz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xwzz.getE4(), V.z, 1e-5f);
	auto xwzw = V.xwzw;
	BOOST_CHECK_CLOSE(xwzw.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwzw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xwzw.getE4(), V.w, 1e-5f);
	auto xwwx = V.xwwx;
	BOOST_CHECK_CLOSE(xwwx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwwx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwwx.getE4(), V.x, 1e-5f);
	auto xwwy = V.xwwy;
	BOOST_CHECK_CLOSE(xwwy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwwy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwwy.getE4(), V.y, 1e-5f);
	auto xwwz = V.xwwz;
	BOOST_CHECK_CLOSE(xwwz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwwz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwwz.getE4(), V.z, 1e-5f);
	auto xwww = V.xwww;
	BOOST_CHECK_CLOSE(xwww.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xwww.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(xwww.getE4(), V.w, 1e-5f);
	auto yxxx = V.yxxx;
	BOOST_CHECK_CLOSE(yxxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxx.getE4(), V.x, 1e-5f);
	auto yxxy = V.yxxy;
	BOOST_CHECK_CLOSE(yxxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxy.getE4(), V.y, 1e-5f);
	auto yxxz = V.yxxz;
	BOOST_CHECK_CLOSE(yxxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxz.getE4(), V.z, 1e-5f);
	auto yxxw = V.yxxw;
	BOOST_CHECK_CLOSE(yxxw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxxw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxw.getE4(), V.w, 1e-5f);
	auto yxyx = V.yxyx;
	BOOST_CHECK_CLOSE(yxyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyx.getE4(), V.x, 1e-5f);
	auto yxyy = V.yxyy;
	BOOST_CHECK_CLOSE(yxyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyy.getE4(), V.y, 1e-5f);
	auto yxyz = V.yxyz;
	BOOST_CHECK_CLOSE(yxyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyz.getE4(), V.z, 1e-5f);
	auto yxyw = V.yxyw;
	BOOST_CHECK_CLOSE(yxyw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyw.getE4(), V.w, 1e-5f);
	auto yxzx = V.yxzx;
	BOOST_CHECK_CLOSE(yxzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxzx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yxzx.getE4(), V.x, 1e-5f);
	auto yxzy = V.yxzy;
	BOOST_CHECK_CLOSE(yxzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxzy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yxzy.getE4(), V.y, 1e-5f);
	auto yxzz = V.yxzz;
	BOOST_CHECK_CLOSE(yxzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxzz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yxzz.getE4(), V.z, 1e-5f);
	auto yxzw = V.yxzw;
	BOOST_CHECK_CLOSE(yxzw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxzw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yxzw.getE4(), V.w, 1e-5f);
	auto yxwx = V.yxwx;
	BOOST_CHECK_CLOSE(yxwx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxwx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yxwx.getE4(), V.x, 1e-5f);
	auto yxwy = V.yxwy;
	BOOST_CHECK_CLOSE(yxwy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxwy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yxwy.getE4(), V.y, 1e-5f);
	auto yxwz = V.yxwz;
	BOOST_CHECK_CLOSE(yxwz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxwz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yxwz.getE4(), V.z, 1e-5f);
	auto yxww = V.yxww;
	BOOST_CHECK_CLOSE(yxww.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxww.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yxww.getE4(), V.w, 1e-5f);
	auto yyxx = V.yyxx;
	BOOST_CHECK_CLOSE(yyxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yyxx.getE4(), V.x, 1e-5f);
	auto yyxy = V.yyxy;
	BOOST_CHECK_CLOSE(yyxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yyxy.getE4(), V.y, 1e-5f);
	auto yyxz = V.yyxz;
	BOOST_CHECK_CLOSE(yyxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yyxz.getE4(), V.z, 1e-5f);
	auto yyxw = V.yyxw;
	BOOST_CHECK_CLOSE(yyxw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yyxw.getE4(), V.w, 1e-5f);
	auto yyyx = V.yyyx;
	BOOST_CHECK_CLOSE(yyyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyx.getE4(), V.x, 1e-5f);
	auto yyyy = V.yyyy;
	BOOST_CHECK_CLOSE(yyyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyy.getE4(), V.y, 1e-5f);
	auto yyyz = V.yyyz;
	BOOST_CHECK_CLOSE(yyyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyz.getE4(), V.z, 1e-5f);
	auto yyyw = V.yyyw;
	BOOST_CHECK_CLOSE(yyyw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyw.getE4(), V.w, 1e-5f);
	auto yyzx = V.yyzx;
	BOOST_CHECK_CLOSE(yyzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yyzx.getE4(), V.x, 1e-5f);
	auto yyzy = V.yyzy;
	BOOST_CHECK_CLOSE(yyzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yyzy.getE4(), V.y, 1e-5f);
	auto yyzz = V.yyzz;
	BOOST_CHECK_CLOSE(yyzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yyzz.getE4(), V.z, 1e-5f);
	auto yyzw = V.yyzw;
	BOOST_CHECK_CLOSE(yyzw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yyzw.getE4(), V.w, 1e-5f);
	auto yywx = V.yywx;
	BOOST_CHECK_CLOSE(yywx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yywx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yywx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yywx.getE4(), V.x, 1e-5f);
	auto yywy = V.yywy;
	BOOST_CHECK_CLOSE(yywy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yywy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yywy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yywy.getE4(), V.y, 1e-5f);
	auto yywz = V.yywz;
	BOOST_CHECK_CLOSE(yywz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yywz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yywz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yywz.getE4(), V.z, 1e-5f);
	auto yyww = V.yyww;
	BOOST_CHECK_CLOSE(yyww.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyww.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yyww.getE4(), V.w, 1e-5f);
	auto yzxx = V.yzxx;
	BOOST_CHECK_CLOSE(yzxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzxx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yzxx.getE4(), V.x, 1e-5f);
	auto yzxy = V.yzxy;
	BOOST_CHECK_CLOSE(yzxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzxy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yzxy.getE4(), V.y, 1e-5f);
	auto yzxz = V.yzxz;
	BOOST_CHECK_CLOSE(yzxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzxz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yzxz.getE4(), V.z, 1e-5f);
	auto yzxw = V.yzxw;
	BOOST_CHECK_CLOSE(yzxw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzxw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yzxw.getE4(), V.w, 1e-5f);
	auto yzyx = V.yzyx;
	BOOST_CHECK_CLOSE(yzyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyx.getE4(), V.x, 1e-5f);
	auto yzyy = V.yzyy;
	BOOST_CHECK_CLOSE(yzyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyy.getE4(), V.y, 1e-5f);
	auto yzyz = V.yzyz;
	BOOST_CHECK_CLOSE(yzyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyz.getE4(), V.z, 1e-5f);
	auto yzyw = V.yzyw;
	BOOST_CHECK_CLOSE(yzyw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyw.getE4(), V.w, 1e-5f);
	auto yzzx = V.yzzx;
	BOOST_CHECK_CLOSE(yzzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzx.getE4(), V.x, 1e-5f);
	auto yzzy = V.yzzy;
	BOOST_CHECK_CLOSE(yzzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzy.getE4(), V.y, 1e-5f);
	auto yzzz = V.yzzz;
	BOOST_CHECK_CLOSE(yzzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzz.getE4(), V.z, 1e-5f);
	auto yzzw = V.yzzw;
	BOOST_CHECK_CLOSE(yzzw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzzw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzw.getE4(), V.w, 1e-5f);
	auto yzwx = V.yzwx;
	BOOST_CHECK_CLOSE(yzwx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzwx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yzwx.getE4(), V.x, 1e-5f);
	auto yzwy = V.yzwy;
	BOOST_CHECK_CLOSE(yzwy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzwy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yzwy.getE4(), V.y, 1e-5f);
	auto yzwz = V.yzwz;
	BOOST_CHECK_CLOSE(yzwz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzwz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yzwz.getE4(), V.z, 1e-5f);
	auto yzww = V.yzww;
	BOOST_CHECK_CLOSE(yzww.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzww.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(yzww.getE4(), V.w, 1e-5f);
	auto ywxx = V.ywxx;
	BOOST_CHECK_CLOSE(ywxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywxx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(ywxx.getE4(), V.x, 1e-5f);
	auto ywxy = V.ywxy;
	BOOST_CHECK_CLOSE(ywxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywxy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(ywxy.getE4(), V.y, 1e-5f);
	auto ywxz = V.ywxz;
	BOOST_CHECK_CLOSE(ywxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywxz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(ywxz.getE4(), V.z, 1e-5f);
	auto ywxw = V.ywxw;
	BOOST_CHECK_CLOSE(ywxw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywxw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(ywxw.getE4(), V.w, 1e-5f);
	auto ywyx = V.ywyx;
	BOOST_CHECK_CLOSE(ywyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywyx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywyx.getE4(), V.x, 1e-5f);
	auto ywyy = V.ywyy;
	BOOST_CHECK_CLOSE(ywyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywyy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywyy.getE4(), V.y, 1e-5f);
	auto ywyz = V.ywyz;
	BOOST_CHECK_CLOSE(ywyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywyz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywyz.getE4(), V.z, 1e-5f);
	auto ywyw = V.ywyw;
	BOOST_CHECK_CLOSE(ywyw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywyw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywyw.getE4(), V.w, 1e-5f);
	auto ywzx = V.ywzx;
	BOOST_CHECK_CLOSE(ywzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywzx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(ywzx.getE4(), V.x, 1e-5f);
	auto ywzy = V.ywzy;
	BOOST_CHECK_CLOSE(ywzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywzy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(ywzy.getE4(), V.y, 1e-5f);
	auto ywzz = V.ywzz;
	BOOST_CHECK_CLOSE(ywzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywzz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(ywzz.getE4(), V.z, 1e-5f);
	auto ywzw = V.ywzw;
	BOOST_CHECK_CLOSE(ywzw.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywzw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(ywzw.getE4(), V.w, 1e-5f);
	auto ywwx = V.ywwx;
	BOOST_CHECK_CLOSE(ywwx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywwx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywwx.getE4(), V.x, 1e-5f);
	auto ywwy = V.ywwy;
	BOOST_CHECK_CLOSE(ywwy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywwy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywwy.getE4(), V.y, 1e-5f);
	auto ywwz = V.ywwz;
	BOOST_CHECK_CLOSE(ywwz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywwz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywwz.getE4(), V.z, 1e-5f);
	auto ywww = V.ywww;
	BOOST_CHECK_CLOSE(ywww.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(ywww.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(ywww.getE4(), V.w, 1e-5f);
	auto zxxx = V.zxxx;
	BOOST_CHECK_CLOSE(zxxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxx.getE4(), V.x, 1e-5f);
	auto zxxy = V.zxxy;
	BOOST_CHECK_CLOSE(zxxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxy.getE4(), V.y, 1e-5f);
	auto zxxz = V.zxxz;
	BOOST_CHECK_CLOSE(zxxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxz.getE4(), V.z, 1e-5f);
	auto zxxw = V.zxxw;
	BOOST_CHECK_CLOSE(zxxw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxxw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxw.getE4(), V.w, 1e-5f);
	auto zxyx = V.zxyx;
	BOOST_CHECK_CLOSE(zxyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxyx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zxyx.getE4(), V.x, 1e-5f);
	auto zxyy = V.zxyy;
	BOOST_CHECK_CLOSE(zxyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxyy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zxyy.getE4(), V.y, 1e-5f);
	auto zxyz = V.zxyz;
	BOOST_CHECK_CLOSE(zxyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxyz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zxyz.getE4(), V.z, 1e-5f);
	auto zxyw = V.zxyw;
	BOOST_CHECK_CLOSE(zxyw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxyw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zxyw.getE4(), V.w, 1e-5f);
	auto zxzx = V.zxzx;
	BOOST_CHECK_CLOSE(zxzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzx.getE4(), V.x, 1e-5f);
	auto zxzy = V.zxzy;
	BOOST_CHECK_CLOSE(zxzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzy.getE4(), V.y, 1e-5f);
	auto zxzz = V.zxzz;
	BOOST_CHECK_CLOSE(zxzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzz.getE4(), V.z, 1e-5f);
	auto zxzw = V.zxzw;
	BOOST_CHECK_CLOSE(zxzw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzw.getE4(), V.w, 1e-5f);
	auto zxwx = V.zxwx;
	BOOST_CHECK_CLOSE(zxwx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxwx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zxwx.getE4(), V.x, 1e-5f);
	auto zxwy = V.zxwy;
	BOOST_CHECK_CLOSE(zxwy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxwy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zxwy.getE4(), V.y, 1e-5f);
	auto zxwz = V.zxwz;
	BOOST_CHECK_CLOSE(zxwz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxwz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zxwz.getE4(), V.z, 1e-5f);
	auto zxww = V.zxww;
	BOOST_CHECK_CLOSE(zxww.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxww.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zxww.getE4(), V.w, 1e-5f);
	auto zyxx = V.zyxx;
	BOOST_CHECK_CLOSE(zyxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyxx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zyxx.getE4(), V.x, 1e-5f);
	auto zyxy = V.zyxy;
	BOOST_CHECK_CLOSE(zyxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyxy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zyxy.getE4(), V.y, 1e-5f);
	auto zyxz = V.zyxz;
	BOOST_CHECK_CLOSE(zyxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyxz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zyxz.getE4(), V.z, 1e-5f);
	auto zyxw = V.zyxw;
	BOOST_CHECK_CLOSE(zyxw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyxw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zyxw.getE4(), V.w, 1e-5f);
	auto zyyx = V.zyyx;
	BOOST_CHECK_CLOSE(zyyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyx.getE4(), V.x, 1e-5f);
	auto zyyy = V.zyyy;
	BOOST_CHECK_CLOSE(zyyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyy.getE4(), V.y, 1e-5f);
	auto zyyz = V.zyyz;
	BOOST_CHECK_CLOSE(zyyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyz.getE4(), V.z, 1e-5f);
	auto zyyw = V.zyyw;
	BOOST_CHECK_CLOSE(zyyw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyyw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyw.getE4(), V.w, 1e-5f);
	auto zyzx = V.zyzx;
	BOOST_CHECK_CLOSE(zyzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzx.getE4(), V.x, 1e-5f);
	auto zyzy = V.zyzy;
	BOOST_CHECK_CLOSE(zyzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzy.getE4(), V.y, 1e-5f);
	auto zyzz = V.zyzz;
	BOOST_CHECK_CLOSE(zyzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzz.getE4(), V.z, 1e-5f);
	auto zyzw = V.zyzw;
	BOOST_CHECK_CLOSE(zyzw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzw.getE4(), V.w, 1e-5f);
	auto zywx = V.zywx;
	BOOST_CHECK_CLOSE(zywx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zywx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zywx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zywx.getE4(), V.x, 1e-5f);
	auto zywy = V.zywy;
	BOOST_CHECK_CLOSE(zywy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zywy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zywy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zywy.getE4(), V.y, 1e-5f);
	auto zywz = V.zywz;
	BOOST_CHECK_CLOSE(zywz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zywz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zywz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zywz.getE4(), V.z, 1e-5f);
	auto zyww = V.zyww;
	BOOST_CHECK_CLOSE(zyww.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyww.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zyww.getE4(), V.w, 1e-5f);
	auto zzxx = V.zzxx;
	BOOST_CHECK_CLOSE(zzxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zzxx.getE4(), V.x, 1e-5f);
	auto zzxy = V.zzxy;
	BOOST_CHECK_CLOSE(zzxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zzxy.getE4(), V.y, 1e-5f);
	auto zzxz = V.zzxz;
	BOOST_CHECK_CLOSE(zzxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zzxz.getE4(), V.z, 1e-5f);
	auto zzxw = V.zzxw;
	BOOST_CHECK_CLOSE(zzxw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zzxw.getE4(), V.w, 1e-5f);
	auto zzyx = V.zzyx;
	BOOST_CHECK_CLOSE(zzyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zzyx.getE4(), V.x, 1e-5f);
	auto zzyy = V.zzyy;
	BOOST_CHECK_CLOSE(zzyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zzyy.getE4(), V.y, 1e-5f);
	auto zzyz = V.zzyz;
	BOOST_CHECK_CLOSE(zzyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zzyz.getE4(), V.z, 1e-5f);
	auto zzyw = V.zzyw;
	BOOST_CHECK_CLOSE(zzyw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zzyw.getE4(), V.w, 1e-5f);
	auto zzzx = V.zzzx;
	BOOST_CHECK_CLOSE(zzzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzx.getE4(), V.x, 1e-5f);
	auto zzzy = V.zzzy;
	BOOST_CHECK_CLOSE(zzzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzy.getE4(), V.y, 1e-5f);
	auto zzzz = V.zzzz;
	BOOST_CHECK_CLOSE(zzzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzz.getE4(), V.z, 1e-5f);
	auto zzzw = V.zzzw;
	BOOST_CHECK_CLOSE(zzzw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzw.getE4(), V.w, 1e-5f);
	auto zzwx = V.zzwx;
	BOOST_CHECK_CLOSE(zzwx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzwx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zzwx.getE4(), V.x, 1e-5f);
	auto zzwy = V.zzwy;
	BOOST_CHECK_CLOSE(zzwy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzwy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zzwy.getE4(), V.y, 1e-5f);
	auto zzwz = V.zzwz;
	BOOST_CHECK_CLOSE(zzwz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzwz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zzwz.getE4(), V.z, 1e-5f);
	auto zzww = V.zzww;
	BOOST_CHECK_CLOSE(zzww.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzww.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zzww.getE4(), V.w, 1e-5f);
	auto zwxx = V.zwxx;
	BOOST_CHECK_CLOSE(zwxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwxx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zwxx.getE4(), V.x, 1e-5f);
	auto zwxy = V.zwxy;
	BOOST_CHECK_CLOSE(zwxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwxy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zwxy.getE4(), V.y, 1e-5f);
	auto zwxz = V.zwxz;
	BOOST_CHECK_CLOSE(zwxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwxz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zwxz.getE4(), V.z, 1e-5f);
	auto zwxw = V.zwxw;
	BOOST_CHECK_CLOSE(zwxw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwxw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zwxw.getE4(), V.w, 1e-5f);
	auto zwyx = V.zwyx;
	BOOST_CHECK_CLOSE(zwyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwyx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zwyx.getE4(), V.x, 1e-5f);
	auto zwyy = V.zwyy;
	BOOST_CHECK_CLOSE(zwyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwyy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zwyy.getE4(), V.y, 1e-5f);
	auto zwyz = V.zwyz;
	BOOST_CHECK_CLOSE(zwyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwyz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zwyz.getE4(), V.z, 1e-5f);
	auto zwyw = V.zwyw;
	BOOST_CHECK_CLOSE(zwyw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwyw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zwyw.getE4(), V.w, 1e-5f);
	auto zwzx = V.zwzx;
	BOOST_CHECK_CLOSE(zwzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwzx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwzx.getE4(), V.x, 1e-5f);
	auto zwzy = V.zwzy;
	BOOST_CHECK_CLOSE(zwzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwzy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwzy.getE4(), V.y, 1e-5f);
	auto zwzz = V.zwzz;
	BOOST_CHECK_CLOSE(zwzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwzz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwzz.getE4(), V.z, 1e-5f);
	auto zwzw = V.zwzw;
	BOOST_CHECK_CLOSE(zwzw.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwzw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwzw.getE4(), V.w, 1e-5f);
	auto zwwx = V.zwwx;
	BOOST_CHECK_CLOSE(zwwx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwwx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwwx.getE4(), V.x, 1e-5f);
	auto zwwy = V.zwwy;
	BOOST_CHECK_CLOSE(zwwy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwwy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwwy.getE4(), V.y, 1e-5f);
	auto zwwz = V.zwwz;
	BOOST_CHECK_CLOSE(zwwz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwwz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwwz.getE4(), V.z, 1e-5f);
	auto zwww = V.zwww;
	BOOST_CHECK_CLOSE(zwww.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zwww.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(zwww.getE4(), V.w, 1e-5f);
	auto wxxx = V.wxxx;
	BOOST_CHECK_CLOSE(wxxx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxxx.getE4(), V.x, 1e-5f);
	auto wxxy = V.wxxy;
	BOOST_CHECK_CLOSE(wxxy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxxy.getE4(), V.y, 1e-5f);
	auto wxxz = V.wxxz;
	BOOST_CHECK_CLOSE(wxxz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxxz.getE4(), V.z, 1e-5f);
	auto wxxw = V.wxxw;
	BOOST_CHECK_CLOSE(wxxw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxxw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxxw.getE4(), V.w, 1e-5f);
	auto wxyx = V.wxyx;
	BOOST_CHECK_CLOSE(wxyx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxyx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wxyx.getE4(), V.x, 1e-5f);
	auto wxyy = V.wxyy;
	BOOST_CHECK_CLOSE(wxyy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxyy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wxyy.getE4(), V.y, 1e-5f);
	auto wxyz = V.wxyz;
	BOOST_CHECK_CLOSE(wxyz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxyz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wxyz.getE4(), V.z, 1e-5f);
	auto wxyw = V.wxyw;
	BOOST_CHECK_CLOSE(wxyw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxyw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wxyw.getE4(), V.w, 1e-5f);
	auto wxzx = V.wxzx;
	BOOST_CHECK_CLOSE(wxzx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxzx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wxzx.getE4(), V.x, 1e-5f);
	auto wxzy = V.wxzy;
	BOOST_CHECK_CLOSE(wxzy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxzy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wxzy.getE4(), V.y, 1e-5f);
	auto wxzz = V.wxzz;
	BOOST_CHECK_CLOSE(wxzz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxzz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wxzz.getE4(), V.z, 1e-5f);
	auto wxzw = V.wxzw;
	BOOST_CHECK_CLOSE(wxzw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxzw.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wxzw.getE4(), V.w, 1e-5f);
	auto wxwx = V.wxwx;
	BOOST_CHECK_CLOSE(wxwx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxwx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxwx.getE4(), V.x, 1e-5f);
	auto wxwy = V.wxwy;
	BOOST_CHECK_CLOSE(wxwy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxwy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxwy.getE4(), V.y, 1e-5f);
	auto wxwz = V.wxwz;
	BOOST_CHECK_CLOSE(wxwz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxwz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxwz.getE4(), V.z, 1e-5f);
	auto wxww = V.wxww;
	BOOST_CHECK_CLOSE(wxww.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxww.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wxww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wxww.getE4(), V.w, 1e-5f);
	auto wyxx = V.wyxx;
	BOOST_CHECK_CLOSE(wyxx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyxx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wyxx.getE4(), V.x, 1e-5f);
	auto wyxy = V.wyxy;
	BOOST_CHECK_CLOSE(wyxy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyxy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wyxy.getE4(), V.y, 1e-5f);
	auto wyxz = V.wyxz;
	BOOST_CHECK_CLOSE(wyxz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyxz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wyxz.getE4(), V.z, 1e-5f);
	auto wyxw = V.wyxw;
	BOOST_CHECK_CLOSE(wyxw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyxw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wyxw.getE4(), V.w, 1e-5f);
	auto wyyx = V.wyyx;
	BOOST_CHECK_CLOSE(wyyx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyyx.getE4(), V.x, 1e-5f);
	auto wyyy = V.wyyy;
	BOOST_CHECK_CLOSE(wyyy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyyy.getE4(), V.y, 1e-5f);
	auto wyyz = V.wyyz;
	BOOST_CHECK_CLOSE(wyyz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyyz.getE4(), V.z, 1e-5f);
	auto wyyw = V.wyyw;
	BOOST_CHECK_CLOSE(wyyw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyyw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyyw.getE4(), V.w, 1e-5f);
	auto wyzx = V.wyzx;
	BOOST_CHECK_CLOSE(wyzx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyzx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wyzx.getE4(), V.x, 1e-5f);
	auto wyzy = V.wyzy;
	BOOST_CHECK_CLOSE(wyzy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyzy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wyzy.getE4(), V.y, 1e-5f);
	auto wyzz = V.wyzz;
	BOOST_CHECK_CLOSE(wyzz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyzz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wyzz.getE4(), V.z, 1e-5f);
	auto wyzw = V.wyzw;
	BOOST_CHECK_CLOSE(wyzw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyzw.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wyzw.getE4(), V.w, 1e-5f);
	auto wywx = V.wywx;
	BOOST_CHECK_CLOSE(wywx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wywx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wywx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wywx.getE4(), V.x, 1e-5f);
	auto wywy = V.wywy;
	BOOST_CHECK_CLOSE(wywy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wywy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wywy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wywy.getE4(), V.y, 1e-5f);
	auto wywz = V.wywz;
	BOOST_CHECK_CLOSE(wywz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wywz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wywz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wywz.getE4(), V.z, 1e-5f);
	auto wyww = V.wyww;
	BOOST_CHECK_CLOSE(wyww.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyww.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wyww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wyww.getE4(), V.w, 1e-5f);
	auto wzxx = V.wzxx;
	BOOST_CHECK_CLOSE(wzxx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzxx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wzxx.getE4(), V.x, 1e-5f);
	auto wzxy = V.wzxy;
	BOOST_CHECK_CLOSE(wzxy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzxy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wzxy.getE4(), V.y, 1e-5f);
	auto wzxz = V.wzxz;
	BOOST_CHECK_CLOSE(wzxz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzxz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wzxz.getE4(), V.z, 1e-5f);
	auto wzxw = V.wzxw;
	BOOST_CHECK_CLOSE(wzxw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzxw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wzxw.getE4(), V.w, 1e-5f);
	auto wzyx = V.wzyx;
	BOOST_CHECK_CLOSE(wzyx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzyx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wzyx.getE4(), V.x, 1e-5f);
	auto wzyy = V.wzyy;
	BOOST_CHECK_CLOSE(wzyy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzyy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wzyy.getE4(), V.y, 1e-5f);
	auto wzyz = V.wzyz;
	BOOST_CHECK_CLOSE(wzyz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzyz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wzyz.getE4(), V.z, 1e-5f);
	auto wzyw = V.wzyw;
	BOOST_CHECK_CLOSE(wzyw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzyw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wzyw.getE4(), V.w, 1e-5f);
	auto wzzx = V.wzzx;
	BOOST_CHECK_CLOSE(wzzx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzzx.getE4(), V.x, 1e-5f);
	auto wzzy = V.wzzy;
	BOOST_CHECK_CLOSE(wzzy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzzy.getE4(), V.y, 1e-5f);
	auto wzzz = V.wzzz;
	BOOST_CHECK_CLOSE(wzzz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzzz.getE4(), V.z, 1e-5f);
	auto wzzw = V.wzzw;
	BOOST_CHECK_CLOSE(wzzw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzzw.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzzw.getE4(), V.w, 1e-5f);
	auto wzwx = V.wzwx;
	BOOST_CHECK_CLOSE(wzwx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzwx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzwx.getE4(), V.x, 1e-5f);
	auto wzwy = V.wzwy;
	BOOST_CHECK_CLOSE(wzwy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzwy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzwy.getE4(), V.y, 1e-5f);
	auto wzwz = V.wzwz;
	BOOST_CHECK_CLOSE(wzwz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzwz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzwz.getE4(), V.z, 1e-5f);
	auto wzww = V.wzww;
	BOOST_CHECK_CLOSE(wzww.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzww.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wzww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wzww.getE4(), V.w, 1e-5f);
	auto wwxx = V.wwxx;
	BOOST_CHECK_CLOSE(wwxx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwxx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wwxx.getE4(), V.x, 1e-5f);
	auto wwxy = V.wwxy;
	BOOST_CHECK_CLOSE(wwxy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwxy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wwxy.getE4(), V.y, 1e-5f);
	auto wwxz = V.wwxz;
	BOOST_CHECK_CLOSE(wwxz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwxz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wwxz.getE4(), V.z, 1e-5f);
	auto wwxw = V.wwxw;
	BOOST_CHECK_CLOSE(wwxw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwxw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwxw.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(wwxw.getE4(), V.w, 1e-5f);
	auto wwyx = V.wwyx;
	BOOST_CHECK_CLOSE(wwyx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwyx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wwyx.getE4(), V.x, 1e-5f);
	auto wwyy = V.wwyy;
	BOOST_CHECK_CLOSE(wwyy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwyy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wwyy.getE4(), V.y, 1e-5f);
	auto wwyz = V.wwyz;
	BOOST_CHECK_CLOSE(wwyz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwyz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wwyz.getE4(), V.z, 1e-5f);
	auto wwyw = V.wwyw;
	BOOST_CHECK_CLOSE(wwyw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwyw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwyw.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(wwyw.getE4(), V.w, 1e-5f);
	auto wwzx = V.wwzx;
	BOOST_CHECK_CLOSE(wwzx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwzx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wwzx.getE4(), V.x, 1e-5f);
	auto wwzy = V.wwzy;
	BOOST_CHECK_CLOSE(wwzy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwzy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wwzy.getE4(), V.y, 1e-5f);
	auto wwzz = V.wwzz;
	BOOST_CHECK_CLOSE(wwzz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwzz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wwzz.getE4(), V.z, 1e-5f);
	auto wwzw = V.wwzw;
	BOOST_CHECK_CLOSE(wwzw.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwzw.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwzw.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(wwzw.getE4(), V.w, 1e-5f);
	auto wwwx = V.wwwx;
	BOOST_CHECK_CLOSE(wwwx.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwx.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwx.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwx.getE4(), V.x, 1e-5f);
	auto wwwy = V.wwwy;
	BOOST_CHECK_CLOSE(wwwy.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwy.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwy.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwy.getE4(), V.y, 1e-5f);
	auto wwwz = V.wwwz;
	BOOST_CHECK_CLOSE(wwwz.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwz.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwz.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwwz.getE4(), V.z, 1e-5f);
	auto wwww = V.wwww;
	BOOST_CHECK_CLOSE(wwww.getE1(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwww.getE2(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwww.getE3(), V.w, 1e-5f);
	BOOST_CHECK_CLOSE(wwww.getE4(), V.w, 1e-5f);
}

BOOST_AUTO_TEST_CASE(assign) {
	math::Vector2 V2;
	V2.x = 20.12f;
	V2.y = 100.89f;
	math::Vector3 V3;
	V3.x = 20.12f;
	V3.y = 100.89f;
	V3.z = -18.2f;
	math::Vector4 V4;
	V4.x = 20.12f;
	V4.y = 100.89f;
	V4.z = -18.2f;
	V4.w = 35.62f;
	math::Vector4 V;
	V.x = 0.0f;
	V.y = 0.0f;
	V.z = 0.0f;
	V.w = 0.0f;
	// 2d swizzle assign <x, y, z, w> from vector
	V.xy = V2;
	BOOST_CHECK_CLOSE(V.x, V2.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V2.y, 1e-5f);
	BOOST_CHECK_SMALL(V.z, 1e-10f);
	BOOST_CHECK_SMALL(V.w, 1e-10f);
	V.wz = V2;
	BOOST_CHECK_CLOSE(V.x, V2.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V2.x, 1e-5f);
	V.yw = V2;
	BOOST_CHECK_CLOSE(V.x, V2.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V2.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V2.y, 1e-5f);
	// 2d swizzle assign <x, y, z, w> from swizzle
	V.xy = V2.yy;
	BOOST_CHECK_CLOSE(V.x, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V2.y, 1e-5f);
	V.yz = V2.xy;
	BOOST_CHECK_CLOSE(V.x, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V2.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V2.y, 1e-5f);
	V.zw = V2.xx;
	BOOST_CHECK_CLOSE(V.x, V2.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V2.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V2.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V2.x, 1e-5f);
	// 3d swizzle assign <x, y, z, w> from vector
	V.xyz = V3;
	BOOST_CHECK_CLOSE(V.x, V3.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V3.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V3.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V2.x, 1e-5f);
	V.zxw = V3;
	BOOST_CHECK_CLOSE(V.x, V3.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V3.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V3.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V3.z, 1e-5f);
	V.wxy = V3;
	BOOST_CHECK_CLOSE(V.x, V3.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V3.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V3.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V3.x, 1e-5f);
	// 3d swizzle assign <x, y, z, w> from swizzle
	V.xyz = V3.xyz;
	BOOST_CHECK_CLOSE(V.x, V3.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V3.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V3.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V3.x, 1e-5f);
	V.zxw = V3.zzz;
	BOOST_CHECK_CLOSE(V.x, V3.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V3.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V3.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V3.z, 1e-5f);
	V.wxy = V3.yyx;
	BOOST_CHECK_CLOSE(V.x, V3.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V3.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V3.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V3.y, 1e-5f);
	// 4d swizzle assign <x, y, z, w> from vector
	V.xzyw = V4;
	BOOST_CHECK_CLOSE(V.x, V4.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V4.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V4.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V4.w, 1e-5f);
	V.yxzw = V4;
	BOOST_CHECK_CLOSE(V.x, V4.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V4.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V4.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V4.w, 1e-5f);
	V.zwyx = V4;
	BOOST_CHECK_CLOSE(V.x, V4.w, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V4.z, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V4.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V4.y, 1e-5f);
	// 4d swizzle assign <x, y, z, w> from swizzle
	V.xzyw = V4.xxxx;
	BOOST_CHECK_CLOSE(V.x, V4.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V4.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V4.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V4.x, 1e-5f);
	V.yxzw = V4.wwyy;
	BOOST_CHECK_CLOSE(V.x, V4.w, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V4.w, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V4.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V4.y, 1e-5f);
	V.zwyx = V4.wzyx;
	BOOST_CHECK_CLOSE(V.x, V4.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V4.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V4.w, 1e-5f);
	BOOST_CHECK_CLOSE(V.w, V4.z, 1e-5f);
}

BOOST_AUTO_TEST_SUITE_END()
