#define BOOST_TEST_DYN_LINK
#include <boost/test/unit_test.hpp>

#include <utility>

#define MATH_CORE_SWIZZLE_ENABLE_ELEMENT_ACCESSORS
#include <math/types.hpp>

BOOST_AUTO_TEST_SUITE(Vector3)

BOOST_AUTO_TEST_CASE(create) {
	// default constructor
	math::Vector3 V_default;
	BOOST_CHECK_SMALL(V_default.x, 1e-10f);
	BOOST_CHECK_SMALL(V_default.y, 1e-10f);
	BOOST_CHECK_SMALL(V_default.z, 1e-10f);
	// parameterized constructor
	math::Vector3 V_param(1.0f, 2.0f, 3.0f);
	BOOST_CHECK_CLOSE(V_param.x, 1.0f, 1e-5f);
	BOOST_CHECK_CLOSE(V_param.y, 2.0f, 1e-5f);
	BOOST_CHECK_CLOSE(V_param.z, 3.0f, 1e-5f);
	// copy vector2
	// FIXME Until inheriting constructors are available in Visual Studio this
	// won't work.
	/* math::Vector2 V2; */
	/* V2.x = 3.0f; */
	/* V2.y = 2.0f; */
	/* math::Vector3 V_param2(V2, 1.0f); */
	/* BOOST_CHECK_CLOSE(V_param2.x, 3.0f, 1e-5f); */
	/* BOOST_CHECK_CLOSE(V_param2.y, 2.0f, 1e-5f); */
	/* BOOST_CHECK_CLOSE(V_param2.z, 1.0f, 1e-5f); */
}

BOOST_AUTO_TEST_CASE(copy) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	math::Vector3 V_copy(V);
	BOOST_CHECK_CLOSE(V_copy.x, V.x, 1e-5f);
	BOOST_CHECK_CLOSE(V_copy.y, V.y, 1e-5f);
	BOOST_CHECK_CLOSE(V_copy.z, V.z, 1e-5f);
}

BOOST_AUTO_TEST_CASE(move) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	math::Vector3 V_move(std::move(V));
	BOOST_CHECK_CLOSE(V_move.x, V.x, 1e-5f);
	BOOST_CHECK_CLOSE(V_move.y, V.y, 1e-5f);
	BOOST_CHECK_CLOSE(V_move.z, V.z, 1e-5f);
}

BOOST_AUTO_TEST_CASE(members) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	BOOST_CHECK_CLOSE(V.x, V.r, 1e-5f);
	BOOST_CHECK_CLOSE(V.x, V.s, 1e-5f);
	BOOST_CHECK_CLOSE(V.r, V.s, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V.g, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V.t, 1e-5f);
	BOOST_CHECK_CLOSE(V.g, V.t, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V.b, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V.p, 1e-5f);
	BOOST_CHECK_CLOSE(V.b, V.p, 1e-5f);
	V.r = 100.89f;
	V.g = 20.12f;
	V.b = -18.2f;
	BOOST_CHECK_CLOSE(V.x, V.r, 1e-5f);
	BOOST_CHECK_CLOSE(V.x, V.s, 1e-5f);
	BOOST_CHECK_CLOSE(V.r, V.s, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V.g, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V.t, 1e-5f);
	BOOST_CHECK_CLOSE(V.g, V.t, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V.b, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V.p, 1e-5f);
	BOOST_CHECK_CLOSE(V.b, V.p, 1e-5f);
	V.s = 20.12f;
	V.t = 100.89f;
	V.p = -18.2f;
	BOOST_CHECK_CLOSE(V.x, V.r, 1e-5f);
	BOOST_CHECK_CLOSE(V.x, V.s, 1e-5f);
	BOOST_CHECK_CLOSE(V.r, V.s, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V.g, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V.t, 1e-5f);
	BOOST_CHECK_CLOSE(V.g, V.t, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V.b, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V.p, 1e-5f);
	BOOST_CHECK_CLOSE(V.b, V.p, 1e-5f);
}

BOOST_AUTO_TEST_CASE(assign) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	math::Vector3 V_assign;
	V_assign = V;
	BOOST_CHECK_CLOSE(V_assign.x, V.x, 1e-5f);
	BOOST_CHECK_CLOSE(V_assign.y, V.y, 1e-5f);
	BOOST_CHECK_CLOSE(V_assign.z, V.z, 1e-5f);
}

BOOST_AUTO_TEST_CASE(negate) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	math::Vector3 V_neg;
	V_neg = -V;
	BOOST_CHECK_CLOSE(V_neg.x, -20.12f, 1e-5f);
	BOOST_CHECK_CLOSE(V_neg.y, -100.89f, 1e-5f);
	BOOST_CHECK_CLOSE(V_neg.z, 18.2f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(add) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_add;
	V_add = V1 + V2;
	BOOST_CHECK_CLOSE(V_add.x, 30.46f, 1e-5f);
	BOOST_CHECK_CLOSE(V_add.y, 85.39f, 1e-5f);
	BOOST_CHECK_CLOSE(V_add.z, 2.0f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(add_eq) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_add = V1;
	V_add += V2;
	BOOST_CHECK_CLOSE(V_add.x, 30.46f, 1e-5f);
	BOOST_CHECK_CLOSE(V_add.y, 85.39f, 1e-5f);
	BOOST_CHECK_CLOSE(V_add.z, 2.0f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(sub) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_sub;
	V_sub = V1 - V2;
	BOOST_CHECK_CLOSE(V_sub.x, 9.78f, 1e-5f);
	BOOST_CHECK_CLOSE(V_sub.y, 116.39f, 1e-5f);
	BOOST_CHECK_CLOSE(V_sub.z, -38.4f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(sub_eq) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_sub = V1;
	V_sub -= V2;
	BOOST_CHECK_CLOSE(V_sub.x, 9.78f, 1e-5f);
	BOOST_CHECK_CLOSE(V_sub.y, 116.39f, 1e-5f);
	BOOST_CHECK_CLOSE(V_sub.z, -38.4f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(mult) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_mult;
	V_mult = V1 * V2;
	BOOST_CHECK_CLOSE(V_mult.x, 208.0408f, 1e-5f);
	BOOST_CHECK_CLOSE(V_mult.y, -1563.795f, 1e-5f);
	BOOST_CHECK_CLOSE(V_mult.z, -367.64f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(mult_eq) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_mult = V1;
	V_mult *= V2;
	BOOST_CHECK_CLOSE(V_mult.x, 208.0408f, 1e-5f);
	BOOST_CHECK_CLOSE(V_mult.y, -1563.795f, 1e-5f);
	BOOST_CHECK_CLOSE(V_mult.z, -367.64f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(div) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_div;
	V_div = V1 / V2;
	BOOST_CHECK_CLOSE(V_div.x, 1.9458413926499034f, 1e-5f);
	BOOST_CHECK_CLOSE(V_div.y, -6.509032258064516f, 1e-5f);
	BOOST_CHECK_CLOSE(V_div.z, -0.900990099009901f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(div_eq) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_div = V1;
	V_div /= V2;
	BOOST_CHECK_CLOSE(V_div.x, 1.9458413926499034f, 1e-5f);
	BOOST_CHECK_CLOSE(V_div.y, -6.509032258064516f, 1e-5f);
	BOOST_CHECK_CLOSE(V_div.z, -0.900990099009901f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(scalar_mult) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	float s = -34.45f;
	math::Vector3 V_mult;
	V_mult = s * V;
	BOOST_CHECK_CLOSE(V_mult.x, -693.134f, 1e-5f);
	BOOST_CHECK_CLOSE(V_mult.y, -3475.6605f, 1e-5f);
	BOOST_CHECK_CLOSE(V_mult.z, 626.99f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(scalar_div) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	float s = -34.45f;
	math::Vector3 V_div;
	V_div = V / s;
	BOOST_CHECK_CLOSE(V_div.x, -0.5840348330914369f, 1e-5f);
	BOOST_CHECK_CLOSE(V_div.y, -2.9285921625544264f, 1e-5f);
	BOOST_CHECK_CLOSE(V_div.z, 0.5283018867924527f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(mag) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	float mag = V.mag();
	BOOST_CHECK_CLOSE(mag, 104.47414273397987f, 1e-5f);
	V.x = 1.0f;
	V.y = 0.0f;
	V.z = 0.0f;
	mag = V.mag();
	BOOST_CHECK_CLOSE(mag, 1.0f, 1e-5f);
	V.x = 0.0f;
	V.y = 0.0f;
	V.z = 0.0f;
	mag = V.mag();
	BOOST_CHECK_SMALL(mag, 1e-10f);
}

BOOST_AUTO_TEST_CASE(mag2) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	float mag2 = V.mag2();
	BOOST_CHECK_CLOSE(mag2, 10914.8465f, 1e-5f);
	V.x = 1.0f;
	V.y = 0.0f;
	V.z = 0.0f;
	mag2 = V.mag2();
	BOOST_CHECK_CLOSE(mag2, 1.0f, 1e-5f);
	V.x = 0.0f;
	V.y = 0.0f;
	V.z = 0.0f;
	mag2 = V.mag2();
	BOOST_CHECK_SMALL(mag2, 1e-10f);
}

BOOST_AUTO_TEST_CASE(normal) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	math::Vector3 V_norm(V.normal());
	BOOST_CHECK_CLOSE(V_norm.x, 0.19258353764367417f, 1e-5f);
	BOOST_CHECK_CLOSE(V_norm.y, 0.96569346754615f, 1e-5f);
	BOOST_CHECK_CLOSE(V_norm.z, -0.17420578454845276f, 1e-5f);
	V.x = 1.0f;
	V.y = 0.0f;
	V.z = 0.0f;
	V_norm = V.normal();
	BOOST_CHECK_CLOSE(V_norm.x, 1.0f, 1e-5f);
	BOOST_CHECK_SMALL(V_norm.y, 1e-10f);
	BOOST_CHECK_SMALL(V_norm.z, 1e-10f);
}

BOOST_AUTO_TEST_CASE(normalize) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	V.normalize();
	BOOST_CHECK_CLOSE(V.x, 0.19258353764367417f, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, 0.96569346754615f, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, -0.17420578454845276f, 1e-5f);
	V.x = 1.0f;
	V.y = 0.0f;
	V.z = 0.0f;
	math::Vector3 V_norm;
	V_norm = V.normalize();
	BOOST_CHECK_CLOSE(V_norm.x, 1.0f, 1e-5f);
	BOOST_CHECK_SMALL(V.y, 1e-10f);
	BOOST_CHECK_SMALL(V.z, 1e-10f);
}

BOOST_AUTO_TEST_CASE(equals) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V3;
	V3.x = 20.12f;
	V3.y = 100.89f;
	V3.z = -18.2f;
	BOOST_CHECK(V1 != V2);
	BOOST_CHECK(V2 != V3);
	BOOST_CHECK(V1 == V1);
	BOOST_CHECK(V1 == V3);
}

BOOST_AUTO_TEST_CASE(dot) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	float dot = math::Vector3::dot(V1, V2);
	BOOST_CHECK_CLOSE(dot, -1723.3942f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(cross) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 cross = math::Vector3::cross(V1, V2);
	BOOST_CHECK_CLOSE(cross.x, 1755.878f, 1e-5f);
	BOOST_CHECK_CLOSE(cross.y, -594.612061f, 1e-5f);
	BOOST_CHECK_CLOSE(cross.z, -1355.0626f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(reflect) {
	math::Vector3 I;
	I.x = -1.0f;
	I.y = -1.0f;
	I.z = 0.0f;
	math::Vector3 N;
	N.x = 1.0f;
	N.y = 0.0f;
	N.z = 0.0f;
	math::Vector3 R = math::Vector3::reflect(I, N);
	BOOST_CHECK_CLOSE(R.x, 1.0f, 1e-5f);
	BOOST_CHECK_CLOSE(R.y, -1.0f, 1e-5f);
	BOOST_CHECK_SMALL(R.z, 1e-10f);
}

BOOST_AUTO_TEST_CASE(refract) {
	math::Vector3 I;
	I.x = -1.0f;
	I.y = -1.0f;
	I.z = 0.0f;
	math::Vector3 N;
	N.x = 1.0f;
	N.y = 0.0f;
	N.z = 0.0f;
	float eta = 0.2f;
	math::Vector3 R = math::Vector3::refract(I, N, eta);
	BOOST_CHECK_CLOSE(R.x, -1.0f, 1e-5f);
	BOOST_CHECK_CLOSE(R.y, -0.2f, 1e-5f);
	BOOST_CHECK_SMALL(R.z, 1e-10f);
}

BOOST_AUTO_TEST_CASE(lerp) {
	math::Vector3 V1;
	V1.x = 20.12f;
	V1.y = 100.89f;
	V1.z = -18.2f;
	math::Vector3 V2;
	V2.x = 10.34f;
	V2.y = -15.5f;
	V2.z = 20.2f;
	math::Vector3 V_lerp;
	V_lerp = math::Vector3::lerp(V1, V2, 0.5f);
	BOOST_CHECK_CLOSE(V_lerp.x, 15.23f, 1e-5f);
	BOOST_CHECK_CLOSE(V_lerp.y, 42.695f, 1e-5f);
	BOOST_CHECK_CLOSE(V_lerp.z, 1.0f, 1e-5f);
}

BOOST_AUTO_TEST_CASE(swizzle_access) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	// 2d swizzles <x, y, z>
	auto xx = V.xx;
	BOOST_CHECK_CLOSE(xx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xx.getE2(), V.x, 1e-5f);
	auto xy = V.xy;
	BOOST_CHECK_CLOSE(xy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xy.getE2(), V.y, 1e-5f);
	auto xz = V.xz;
	BOOST_CHECK_CLOSE(xz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xz.getE2(), V.z, 1e-5f);
	auto yx = V.yx;
	BOOST_CHECK_CLOSE(yx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yx.getE2(), V.x, 1e-5f);
	auto yy = V.yy;
	BOOST_CHECK_CLOSE(yy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yy.getE2(), V.y, 1e-5f);
	auto yz = V.yz;
	BOOST_CHECK_CLOSE(yz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yz.getE2(), V.z, 1e-5f);
	auto zx = V.zx;
	BOOST_CHECK_CLOSE(zx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zx.getE2(), V.x, 1e-5f);
	auto zy = V.zy;
	BOOST_CHECK_CLOSE(zy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zy.getE2(), V.y, 1e-5f);
	auto zz = V.zz;
	BOOST_CHECK_CLOSE(zz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zz.getE2(), V.z, 1e-5f);
	// 2d swizzles <r, g, b>
	auto rr = V.rr;
	BOOST_CHECK_CLOSE(rr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rr.getE2(), V.r, 1e-5f);
	auto rg = V.rg;
	BOOST_CHECK_CLOSE(rg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rg.getE2(), V.g, 1e-5f);
	auto rb = V.rb;
	BOOST_CHECK_CLOSE(rb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rb.getE2(), V.b, 1e-5f);
	auto gr = V.gr;
	BOOST_CHECK_CLOSE(gr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gr.getE2(), V.r, 1e-5f);
	auto gg = V.gg;
	BOOST_CHECK_CLOSE(gg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gg.getE2(), V.g, 1e-5f);
	auto gb = V.gb;
	BOOST_CHECK_CLOSE(gb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gb.getE2(), V.b, 1e-5f);
	auto br = V.br;
	BOOST_CHECK_CLOSE(br.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(br.getE2(), V.r, 1e-5f);
	auto bg = V.bg;
	BOOST_CHECK_CLOSE(bg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bg.getE2(), V.g, 1e-5f);
	auto bb = V.bb;
	BOOST_CHECK_CLOSE(bb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bb.getE2(), V.b, 1e-5f);
	// 2d swizzles <s, t, p>
	auto ss = V.ss;
	BOOST_CHECK_CLOSE(ss.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ss.getE2(), V.s, 1e-5f);
	auto st = V.st;
	BOOST_CHECK_CLOSE(st.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(st.getE2(), V.t, 1e-5f);
	auto sp = V.sp;
	BOOST_CHECK_CLOSE(sp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sp.getE2(), V.p, 1e-5f);
	auto ts = V.ts;
	BOOST_CHECK_CLOSE(ts.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ts.getE2(), V.s, 1e-5f);
	auto tt = V.tt;
	BOOST_CHECK_CLOSE(tt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tt.getE2(), V.t, 1e-5f);
	auto tp = V.tp;
	BOOST_CHECK_CLOSE(tp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tp.getE2(), V.p, 1e-5f);
	auto ps = V.ps;
	BOOST_CHECK_CLOSE(ps.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ps.getE2(), V.s, 1e-5f);
	auto pt = V.pt;
	BOOST_CHECK_CLOSE(pt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pt.getE2(), V.t, 1e-5f);
	auto pp = V.pp;
	BOOST_CHECK_CLOSE(pp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pp.getE2(), V.p, 1e-5f);
	// 3d swizzles <x, y, z>
	auto xxx = V.xxx;
	BOOST_CHECK_CLOSE(xxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxx.getE3(), V.x, 1e-5f);
	auto xxy = V.xxy;
	BOOST_CHECK_CLOSE(xxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxy.getE3(), V.y, 1e-5f);
	auto xxz = V.xxz;
	BOOST_CHECK_CLOSE(xxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxz.getE3(), V.z, 1e-5f);
	auto xyx = V.xyx;
	BOOST_CHECK_CLOSE(xyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyx.getE3(), V.x, 1e-5f);
	auto xyy = V.xyy;
	BOOST_CHECK_CLOSE(xyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyy.getE3(), V.y, 1e-5f);
	auto xyz = V.xyz;
	BOOST_CHECK_CLOSE(xyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyz.getE3(), V.z, 1e-5f);
	auto xzx = V.xzx;
	BOOST_CHECK_CLOSE(xzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzx.getE3(), V.x, 1e-5f);
	auto xzy = V.xzy;
	BOOST_CHECK_CLOSE(xzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzy.getE3(), V.y, 1e-5f);
	auto xzz = V.xzz;
	BOOST_CHECK_CLOSE(xzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzz.getE3(), V.z, 1e-5f);
	auto yxx = V.yxx;
	BOOST_CHECK_CLOSE(yxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxx.getE3(), V.x, 1e-5f);
	auto yxy = V.yxy;
	BOOST_CHECK_CLOSE(yxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxy.getE3(), V.y, 1e-5f);
	auto yxz = V.yxz;
	BOOST_CHECK_CLOSE(yxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxz.getE3(), V.z, 1e-5f);
	auto yyx = V.yyx;
	BOOST_CHECK_CLOSE(yyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyx.getE3(), V.x, 1e-5f);
	auto yyy = V.yyy;
	BOOST_CHECK_CLOSE(yyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyy.getE3(), V.y, 1e-5f);
	auto yyz = V.yyz;
	BOOST_CHECK_CLOSE(yyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyz.getE3(), V.z, 1e-5f);
	auto yzx = V.yzx;
	BOOST_CHECK_CLOSE(yzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzx.getE3(), V.x, 1e-5f);
	auto yzy = V.yzy;
	BOOST_CHECK_CLOSE(yzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzy.getE3(), V.y, 1e-5f);
	auto yzz = V.yzz;
	BOOST_CHECK_CLOSE(yzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzz.getE3(), V.z, 1e-5f);
	auto zxx = V.zxx;
	BOOST_CHECK_CLOSE(zxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxx.getE3(), V.x, 1e-5f);
	auto zxy = V.zxy;
	BOOST_CHECK_CLOSE(zxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxy.getE3(), V.y, 1e-5f);
	auto zxz = V.zxz;
	BOOST_CHECK_CLOSE(zxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxz.getE3(), V.z, 1e-5f);
	auto zyx = V.zyx;
	BOOST_CHECK_CLOSE(zyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyx.getE3(), V.x, 1e-5f);
	auto zyy = V.zyy;
	BOOST_CHECK_CLOSE(zyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyy.getE3(), V.y, 1e-5f);
	auto zyz = V.zyz;
	BOOST_CHECK_CLOSE(zyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyz.getE3(), V.z, 1e-5f);
	auto zzx = V.zzx;
	BOOST_CHECK_CLOSE(zzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzx.getE3(), V.x, 1e-5f);
	auto zzy = V.zzy;
	BOOST_CHECK_CLOSE(zzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzy.getE3(), V.y, 1e-5f);
	auto zzz = V.zzz;
	BOOST_CHECK_CLOSE(zzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzz.getE3(), V.z, 1e-5f);
	// 3d swizzles <r, g, b>
	auto rrr = V.rrr;
	BOOST_CHECK_CLOSE(rrr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrr.getE3(), V.r, 1e-5f);
	auto rrg = V.rrg;
	BOOST_CHECK_CLOSE(rrg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrg.getE3(), V.g, 1e-5f);
	auto rrb = V.rrb;
	BOOST_CHECK_CLOSE(rrb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrb.getE3(), V.b, 1e-5f);
	auto rgr = V.rgr;
	BOOST_CHECK_CLOSE(rgr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgr.getE3(), V.r, 1e-5f);
	auto rgg = V.rgg;
	BOOST_CHECK_CLOSE(rgg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgg.getE3(), V.g, 1e-5f);
	auto rgb = V.rgb;
	BOOST_CHECK_CLOSE(rgb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgb.getE3(), V.b, 1e-5f);
	auto rbr = V.rbr;
	BOOST_CHECK_CLOSE(rbr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbr.getE3(), V.r, 1e-5f);
	auto rbg = V.rbg;
	BOOST_CHECK_CLOSE(rbg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbg.getE3(), V.g, 1e-5f);
	auto rbb = V.rbb;
	BOOST_CHECK_CLOSE(rbb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbb.getE3(), V.b, 1e-5f);
	auto grr = V.grr;
	BOOST_CHECK_CLOSE(grr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grr.getE3(), V.r, 1e-5f);
	auto grg = V.grg;
	BOOST_CHECK_CLOSE(grg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grg.getE3(), V.g, 1e-5f);
	auto grb = V.grb;
	BOOST_CHECK_CLOSE(grb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grb.getE3(), V.b, 1e-5f);
	auto ggr = V.ggr;
	BOOST_CHECK_CLOSE(ggr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggr.getE3(), V.r, 1e-5f);
	auto ggg = V.ggg;
	BOOST_CHECK_CLOSE(ggg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggg.getE3(), V.g, 1e-5f);
	auto ggb = V.ggb;
	BOOST_CHECK_CLOSE(ggb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggb.getE3(), V.b, 1e-5f);
	auto gbr = V.gbr;
	BOOST_CHECK_CLOSE(gbr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbr.getE3(), V.r, 1e-5f);
	auto gbg = V.gbg;
	BOOST_CHECK_CLOSE(gbg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbg.getE3(), V.g, 1e-5f);
	auto gbb = V.gbb;
	BOOST_CHECK_CLOSE(gbb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbb.getE3(), V.b, 1e-5f);
	auto brr = V.brr;
	BOOST_CHECK_CLOSE(brr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brr.getE3(), V.r, 1e-5f);
	auto brg = V.brg;
	BOOST_CHECK_CLOSE(brg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brg.getE3(), V.g, 1e-5f);
	auto brb = V.brb;
	BOOST_CHECK_CLOSE(brb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brb.getE3(), V.b, 1e-5f);
	auto bgr = V.bgr;
	BOOST_CHECK_CLOSE(bgr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgr.getE3(), V.r, 1e-5f);
	auto bgg = V.bgg;
	BOOST_CHECK_CLOSE(bgg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgg.getE3(), V.g, 1e-5f);
	auto bgb = V.bgb;
	BOOST_CHECK_CLOSE(bgb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgb.getE3(), V.b, 1e-5f);
	auto bbr = V.bbr;
	BOOST_CHECK_CLOSE(bbr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbr.getE3(), V.r, 1e-5f);
	auto bbg = V.bbg;
	BOOST_CHECK_CLOSE(bbg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbg.getE3(), V.g, 1e-5f);
	auto bbb = V.bbb;
	BOOST_CHECK_CLOSE(bbb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbb.getE3(), V.b, 1e-5f);
	// 3d swizzles <s, t, p>
	auto sss = V.sss;
	BOOST_CHECK_CLOSE(sss.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sss.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sss.getE3(), V.s, 1e-5f);
	auto sst = V.sst;
	BOOST_CHECK_CLOSE(sst.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sst.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sst.getE3(), V.t, 1e-5f);
	auto ssp = V.ssp;
	BOOST_CHECK_CLOSE(ssp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssp.getE3(), V.p, 1e-5f);
	auto sts = V.sts;
	BOOST_CHECK_CLOSE(sts.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sts.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sts.getE3(), V.s, 1e-5f);
	auto stt = V.stt;
	BOOST_CHECK_CLOSE(stt.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stt.getE3(), V.t, 1e-5f);
	auto stp = V.stp;
	BOOST_CHECK_CLOSE(stp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stp.getE3(), V.p, 1e-5f);
	auto sps = V.sps;
	BOOST_CHECK_CLOSE(sps.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sps.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sps.getE3(), V.s, 1e-5f);
	auto spt = V.spt;
	BOOST_CHECK_CLOSE(spt.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(spt.getE3(), V.t, 1e-5f);
	auto spp = V.spp;
	BOOST_CHECK_CLOSE(spp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(spp.getE3(), V.p, 1e-5f);
	auto tss = V.tss;
	BOOST_CHECK_CLOSE(tss.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tss.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tss.getE3(), V.s, 1e-5f);
	auto tst = V.tst;
	BOOST_CHECK_CLOSE(tst.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tst.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tst.getE3(), V.t, 1e-5f);
	auto tsp = V.tsp;
	BOOST_CHECK_CLOSE(tsp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tsp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tsp.getE3(), V.p, 1e-5f);
	auto tts = V.tts;
	BOOST_CHECK_CLOSE(tts.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tts.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tts.getE3(), V.s, 1e-5f);
	auto ttt = V.ttt;
	BOOST_CHECK_CLOSE(ttt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttt.getE3(), V.t, 1e-5f);
	auto ttp = V.ttp;
	BOOST_CHECK_CLOSE(ttp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttp.getE3(), V.p, 1e-5f);
	auto tps = V.tps;
	BOOST_CHECK_CLOSE(tps.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tps.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tps.getE3(), V.s, 1e-5f);
	auto tpt = V.tpt;
	BOOST_CHECK_CLOSE(tpt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tpt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tpt.getE3(), V.t, 1e-5f);
	auto tpp = V.tpp;
	BOOST_CHECK_CLOSE(tpp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tpp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tpp.getE3(), V.p, 1e-5f);
	auto pss = V.pss;
	BOOST_CHECK_CLOSE(pss.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pss.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(pss.getE3(), V.s, 1e-5f);
	auto pst = V.pst;
	BOOST_CHECK_CLOSE(pst.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pst.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(pst.getE3(), V.t, 1e-5f);
	auto psp = V.psp;
	BOOST_CHECK_CLOSE(psp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(psp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(psp.getE3(), V.p, 1e-5f);
	auto pts = V.pts;
	BOOST_CHECK_CLOSE(pts.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pts.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pts.getE3(), V.s, 1e-5f);
	auto ptt = V.ptt;
	BOOST_CHECK_CLOSE(ptt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptt.getE3(), V.t, 1e-5f);
	auto ptp = V.ptp;
	BOOST_CHECK_CLOSE(ptp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptp.getE3(), V.p, 1e-5f);
	auto pps = V.pps;
	BOOST_CHECK_CLOSE(pps.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pps.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pps.getE3(), V.s, 1e-5f);
	auto ppt = V.ppt;
	BOOST_CHECK_CLOSE(ppt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppt.getE3(), V.t, 1e-5f);
	auto ppp = V.ppp;
	BOOST_CHECK_CLOSE(ppp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppp.getE3(), V.p, 1e-5f);
	// 4d swizzles <x, y, z>
	auto xxxx = V.xxxx;
	BOOST_CHECK_CLOSE(xxxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxx.getE4(), V.x, 1e-5f);
	auto xxxy = V.xxxy;
	BOOST_CHECK_CLOSE(xxxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxy.getE4(), V.y, 1e-5f);
	auto xxxz = V.xxxz;
	BOOST_CHECK_CLOSE(xxxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxxz.getE4(), V.z, 1e-5f);
	auto xxyx = V.xxyx;
	BOOST_CHECK_CLOSE(xxyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xxyx.getE4(), V.x, 1e-5f);
	auto xxyy = V.xxyy;
	BOOST_CHECK_CLOSE(xxyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xxyy.getE4(), V.y, 1e-5f);
	auto xxyz = V.xxyz;
	BOOST_CHECK_CLOSE(xxyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xxyz.getE4(), V.z, 1e-5f);
	auto xxzx = V.xxzx;
	BOOST_CHECK_CLOSE(xxzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xxzx.getE4(), V.x, 1e-5f);
	auto xxzy = V.xxzy;
	BOOST_CHECK_CLOSE(xxzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xxzy.getE4(), V.y, 1e-5f);
	auto xxzz = V.xxzz;
	BOOST_CHECK_CLOSE(xxzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xxzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xxzz.getE4(), V.z, 1e-5f);
	auto xyxx = V.xyxx;
	BOOST_CHECK_CLOSE(xyxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxx.getE4(), V.x, 1e-5f);
	auto xyxy = V.xyxy;
	BOOST_CHECK_CLOSE(xyxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxy.getE4(), V.y, 1e-5f);
	auto xyxz = V.xyxz;
	BOOST_CHECK_CLOSE(xyxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyxz.getE4(), V.z, 1e-5f);
	auto xyyx = V.xyyx;
	BOOST_CHECK_CLOSE(xyyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyx.getE4(), V.x, 1e-5f);
	auto xyyy = V.xyyy;
	BOOST_CHECK_CLOSE(xyyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyy.getE4(), V.y, 1e-5f);
	auto xyyz = V.xyyz;
	BOOST_CHECK_CLOSE(xyyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyyz.getE4(), V.z, 1e-5f);
	auto xyzx = V.xyzx;
	BOOST_CHECK_CLOSE(xyzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyzx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xyzx.getE4(), V.x, 1e-5f);
	auto xyzy = V.xyzy;
	BOOST_CHECK_CLOSE(xyzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyzy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xyzy.getE4(), V.y, 1e-5f);
	auto xyzz = V.xyzz;
	BOOST_CHECK_CLOSE(xyzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xyzz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xyzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xyzz.getE4(), V.z, 1e-5f);
	auto xzxx = V.xzxx;
	BOOST_CHECK_CLOSE(xzxx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxx.getE4(), V.x, 1e-5f);
	auto xzxy = V.xzxy;
	BOOST_CHECK_CLOSE(xzxy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxy.getE4(), V.y, 1e-5f);
	auto xzxz = V.xzxz;
	BOOST_CHECK_CLOSE(xzxz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzxz.getE4(), V.z, 1e-5f);
	auto xzyx = V.xzyx;
	BOOST_CHECK_CLOSE(xzyx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzyx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xzyx.getE4(), V.x, 1e-5f);
	auto xzyy = V.xzyy;
	BOOST_CHECK_CLOSE(xzyy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzyy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xzyy.getE4(), V.y, 1e-5f);
	auto xzyz = V.xzyz;
	BOOST_CHECK_CLOSE(xzyz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzyz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(xzyz.getE4(), V.z, 1e-5f);
	auto xzzx = V.xzzx;
	BOOST_CHECK_CLOSE(xzzx.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzx.getE4(), V.x, 1e-5f);
	auto xzzy = V.xzzy;
	BOOST_CHECK_CLOSE(xzzy.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzy.getE4(), V.y, 1e-5f);
	auto xzzz = V.xzzz;
	BOOST_CHECK_CLOSE(xzzz.getE1(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(xzzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(xzzz.getE4(), V.z, 1e-5f);
	auto yxxx = V.yxxx;
	BOOST_CHECK_CLOSE(yxxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxx.getE4(), V.x, 1e-5f);
	auto yxxy = V.yxxy;
	BOOST_CHECK_CLOSE(yxxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxy.getE4(), V.y, 1e-5f);
	auto yxxz = V.yxxz;
	BOOST_CHECK_CLOSE(yxxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxxz.getE4(), V.z, 1e-5f);
	auto yxyx = V.yxyx;
	BOOST_CHECK_CLOSE(yxyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyx.getE4(), V.x, 1e-5f);
	auto yxyy = V.yxyy;
	BOOST_CHECK_CLOSE(yxyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyy.getE4(), V.y, 1e-5f);
	auto yxyz = V.yxyz;
	BOOST_CHECK_CLOSE(yxyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxyz.getE4(), V.z, 1e-5f);
	auto yxzx = V.yxzx;
	BOOST_CHECK_CLOSE(yxzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxzx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yxzx.getE4(), V.x, 1e-5f);
	auto yxzy = V.yxzy;
	BOOST_CHECK_CLOSE(yxzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxzy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yxzy.getE4(), V.y, 1e-5f);
	auto yxzz = V.yxzz;
	BOOST_CHECK_CLOSE(yxzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yxzz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yxzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yxzz.getE4(), V.z, 1e-5f);
	auto yyxx = V.yyxx;
	BOOST_CHECK_CLOSE(yyxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yyxx.getE4(), V.x, 1e-5f);
	auto yyxy = V.yyxy;
	BOOST_CHECK_CLOSE(yyxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yyxy.getE4(), V.y, 1e-5f);
	auto yyxz = V.yyxz;
	BOOST_CHECK_CLOSE(yyxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yyxz.getE4(), V.z, 1e-5f);
	auto yyyx = V.yyyx;
	BOOST_CHECK_CLOSE(yyyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyx.getE4(), V.x, 1e-5f);
	auto yyyy = V.yyyy;
	BOOST_CHECK_CLOSE(yyyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyy.getE4(), V.y, 1e-5f);
	auto yyyz = V.yyyz;
	BOOST_CHECK_CLOSE(yyyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyyz.getE4(), V.z, 1e-5f);
	auto yyzx = V.yyzx;
	BOOST_CHECK_CLOSE(yyzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yyzx.getE4(), V.x, 1e-5f);
	auto yyzy = V.yyzy;
	BOOST_CHECK_CLOSE(yyzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yyzy.getE4(), V.y, 1e-5f);
	auto yyzz = V.yyzz;
	BOOST_CHECK_CLOSE(yyzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yyzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yyzz.getE4(), V.z, 1e-5f);
	auto yzxx = V.yzxx;
	BOOST_CHECK_CLOSE(yzxx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzxx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yzxx.getE4(), V.x, 1e-5f);
	auto yzxy = V.yzxy;
	BOOST_CHECK_CLOSE(yzxy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzxy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yzxy.getE4(), V.y, 1e-5f);
	auto yzxz = V.yzxz;
	BOOST_CHECK_CLOSE(yzxz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzxz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(yzxz.getE4(), V.z, 1e-5f);
	auto yzyx = V.yzyx;
	BOOST_CHECK_CLOSE(yzyx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyx.getE4(), V.x, 1e-5f);
	auto yzyy = V.yzyy;
	BOOST_CHECK_CLOSE(yzyy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyy.getE4(), V.y, 1e-5f);
	auto yzyz = V.yzyz;
	BOOST_CHECK_CLOSE(yzyz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzyz.getE4(), V.z, 1e-5f);
	auto yzzx = V.yzzx;
	BOOST_CHECK_CLOSE(yzzx.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzx.getE4(), V.x, 1e-5f);
	auto yzzy = V.yzzy;
	BOOST_CHECK_CLOSE(yzzy.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzy.getE4(), V.y, 1e-5f);
	auto yzzz = V.yzzz;
	BOOST_CHECK_CLOSE(yzzz.getE1(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(yzzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(yzzz.getE4(), V.z, 1e-5f);
	auto zxxx = V.zxxx;
	BOOST_CHECK_CLOSE(zxxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxxx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxx.getE4(), V.x, 1e-5f);
	auto zxxy = V.zxxy;
	BOOST_CHECK_CLOSE(zxxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxxy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxy.getE4(), V.y, 1e-5f);
	auto zxxz = V.zxxz;
	BOOST_CHECK_CLOSE(zxxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxxz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxxz.getE4(), V.z, 1e-5f);
	auto zxyx = V.zxyx;
	BOOST_CHECK_CLOSE(zxyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxyx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zxyx.getE4(), V.x, 1e-5f);
	auto zxyy = V.zxyy;
	BOOST_CHECK_CLOSE(zxyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxyy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zxyy.getE4(), V.y, 1e-5f);
	auto zxyz = V.zxyz;
	BOOST_CHECK_CLOSE(zxyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxyz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zxyz.getE4(), V.z, 1e-5f);
	auto zxzx = V.zxzx;
	BOOST_CHECK_CLOSE(zxzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzx.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzx.getE4(), V.x, 1e-5f);
	auto zxzy = V.zxzy;
	BOOST_CHECK_CLOSE(zxzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzy.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzy.getE4(), V.y, 1e-5f);
	auto zxzz = V.zxzz;
	BOOST_CHECK_CLOSE(zxzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzz.getE2(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zxzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zxzz.getE4(), V.z, 1e-5f);
	auto zyxx = V.zyxx;
	BOOST_CHECK_CLOSE(zyxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyxx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zyxx.getE4(), V.x, 1e-5f);
	auto zyxy = V.zyxy;
	BOOST_CHECK_CLOSE(zyxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyxy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zyxy.getE4(), V.y, 1e-5f);
	auto zyxz = V.zyxz;
	BOOST_CHECK_CLOSE(zyxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyxz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zyxz.getE4(), V.z, 1e-5f);
	auto zyyx = V.zyyx;
	BOOST_CHECK_CLOSE(zyyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyyx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyx.getE4(), V.x, 1e-5f);
	auto zyyy = V.zyyy;
	BOOST_CHECK_CLOSE(zyyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyyy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyy.getE4(), V.y, 1e-5f);
	auto zyyz = V.zyyz;
	BOOST_CHECK_CLOSE(zyyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyyz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyyz.getE4(), V.z, 1e-5f);
	auto zyzx = V.zyzx;
	BOOST_CHECK_CLOSE(zyzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzx.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzx.getE4(), V.x, 1e-5f);
	auto zyzy = V.zyzy;
	BOOST_CHECK_CLOSE(zyzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzy.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzy.getE4(), V.y, 1e-5f);
	auto zyzz = V.zyzz;
	BOOST_CHECK_CLOSE(zyzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzz.getE2(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zyzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zyzz.getE4(), V.z, 1e-5f);
	auto zzxx = V.zzxx;
	BOOST_CHECK_CLOSE(zzxx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxx.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zzxx.getE4(), V.x, 1e-5f);
	auto zzxy = V.zzxy;
	BOOST_CHECK_CLOSE(zzxy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxy.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zzxy.getE4(), V.y, 1e-5f);
	auto zzxz = V.zzxz;
	BOOST_CHECK_CLOSE(zzxz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzxz.getE3(), V.x, 1e-5f);
	BOOST_CHECK_CLOSE(zzxz.getE4(), V.z, 1e-5f);
	auto zzyx = V.zzyx;
	BOOST_CHECK_CLOSE(zzyx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyx.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zzyx.getE4(), V.x, 1e-5f);
	auto zzyy = V.zzyy;
	BOOST_CHECK_CLOSE(zzyy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyy.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zzyy.getE4(), V.y, 1e-5f);
	auto zzyz = V.zzyz;
	BOOST_CHECK_CLOSE(zzyz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzyz.getE3(), V.y, 1e-5f);
	BOOST_CHECK_CLOSE(zzyz.getE4(), V.z, 1e-5f);
	auto zzzx = V.zzzx;
	BOOST_CHECK_CLOSE(zzzx.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzx.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzx.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzx.getE4(), V.x, 1e-5f);
	auto zzzy = V.zzzy;
	BOOST_CHECK_CLOSE(zzzy.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzy.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzy.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzy.getE4(), V.y, 1e-5f);
	auto zzzz = V.zzzz;
	BOOST_CHECK_CLOSE(zzzz.getE1(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzz.getE2(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzz.getE3(), V.z, 1e-5f);
	BOOST_CHECK_CLOSE(zzzz.getE4(), V.z, 1e-5f);
	// 4dx swizzles <r, g, b>
	auto rrrr = V.rrrr;
	BOOST_CHECK_CLOSE(rrrr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrr.getE4(), V.r, 1e-5f);
	auto rrrg = V.rrrg;
	BOOST_CHECK_CLOSE(rrrg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrg.getE4(), V.g, 1e-5f);
	auto rrrb = V.rrrb;
	BOOST_CHECK_CLOSE(rrrb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrrb.getE4(), V.b, 1e-5f);
	auto rrgr = V.rrgr;
	BOOST_CHECK_CLOSE(rrgr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrgr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrgr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rrgr.getE4(), V.r, 1e-5f);
	auto rrgg = V.rrgg;
	BOOST_CHECK_CLOSE(rrgg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrgg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrgg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rrgg.getE4(), V.g, 1e-5f);
	auto rrgb = V.rrgb;
	BOOST_CHECK_CLOSE(rrgb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrgb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrgb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rrgb.getE4(), V.b, 1e-5f);
	auto rrbr = V.rrbr;
	BOOST_CHECK_CLOSE(rrbr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrbr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rrbr.getE4(), V.r, 1e-5f);
	auto rrbg = V.rrbg;
	BOOST_CHECK_CLOSE(rrbg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrbg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rrbg.getE4(), V.g, 1e-5f);
	auto rrbb = V.rrbb;
	BOOST_CHECK_CLOSE(rrbb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrbb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rrbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rrbb.getE4(), V.b, 1e-5f);
	auto rgrr = V.rgrr;
	BOOST_CHECK_CLOSE(rgrr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgrr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgrr.getE4(), V.r, 1e-5f);
	auto rgrg = V.rgrg;
	BOOST_CHECK_CLOSE(rgrg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgrg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgrg.getE4(), V.g, 1e-5f);
	auto rgrb = V.rgrb;
	BOOST_CHECK_CLOSE(rgrb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgrb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgrb.getE4(), V.b, 1e-5f);
	auto rggr = V.rggr;
	BOOST_CHECK_CLOSE(rggr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rggr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rggr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rggr.getE4(), V.r, 1e-5f);
	auto rggg = V.rggg;
	BOOST_CHECK_CLOSE(rggg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rggg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rggg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rggg.getE4(), V.g, 1e-5f);
	auto rggb = V.rggb;
	BOOST_CHECK_CLOSE(rggb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rggb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rggb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rggb.getE4(), V.b, 1e-5f);
	auto rgbr = V.rgbr;
	BOOST_CHECK_CLOSE(rgbr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgbr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rgbr.getE4(), V.r, 1e-5f);
	auto rgbg = V.rgbg;
	BOOST_CHECK_CLOSE(rgbg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgbg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rgbg.getE4(), V.g, 1e-5f);
	auto rgbb = V.rgbb;
	BOOST_CHECK_CLOSE(rgbb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rgbb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rgbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rgbb.getE4(), V.b, 1e-5f);
	auto rbrr = V.rbrr;
	BOOST_CHECK_CLOSE(rbrr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbrr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbrr.getE4(), V.r, 1e-5f);
	auto rbrg = V.rbrg;
	BOOST_CHECK_CLOSE(rbrg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbrg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbrg.getE4(), V.g, 1e-5f);
	auto rbrb = V.rbrb;
	BOOST_CHECK_CLOSE(rbrb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbrb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbrb.getE4(), V.b, 1e-5f);
	auto rbgr = V.rbgr;
	BOOST_CHECK_CLOSE(rbgr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbgr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbgr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rbgr.getE4(), V.r, 1e-5f);
	auto rbgg = V.rbgg;
	BOOST_CHECK_CLOSE(rbgg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbgg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbgg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rbgg.getE4(), V.g, 1e-5f);
	auto rbgb = V.rbgb;
	BOOST_CHECK_CLOSE(rbgb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbgb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbgb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(rbgb.getE4(), V.b, 1e-5f);
	auto rbbr = V.rbbr;
	BOOST_CHECK_CLOSE(rbbr.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbbr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbbr.getE4(), V.r, 1e-5f);
	auto rbbg = V.rbbg;
	BOOST_CHECK_CLOSE(rbbg.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbbg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbbg.getE4(), V.g, 1e-5f);
	auto rbbb = V.rbbb;
	BOOST_CHECK_CLOSE(rbbb.getE1(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(rbbb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(rbbb.getE4(), V.b, 1e-5f);
	auto grrr = V.grrr;
	BOOST_CHECK_CLOSE(grrr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grrr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grrr.getE4(), V.r, 1e-5f);
	auto grrg = V.grrg;
	BOOST_CHECK_CLOSE(grrg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grrg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grrg.getE4(), V.g, 1e-5f);
	auto grrb = V.grrb;
	BOOST_CHECK_CLOSE(grrb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grrb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grrb.getE4(), V.b, 1e-5f);
	auto grgr = V.grgr;
	BOOST_CHECK_CLOSE(grgr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grgr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grgr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grgr.getE4(), V.r, 1e-5f);
	auto grgg = V.grgg;
	BOOST_CHECK_CLOSE(grgg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grgg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grgg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grgg.getE4(), V.g, 1e-5f);
	auto grgb = V.grgb;
	BOOST_CHECK_CLOSE(grgb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grgb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grgb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grgb.getE4(), V.b, 1e-5f);
	auto grbr = V.grbr;
	BOOST_CHECK_CLOSE(grbr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grbr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(grbr.getE4(), V.r, 1e-5f);
	auto grbg = V.grbg;
	BOOST_CHECK_CLOSE(grbg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grbg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(grbg.getE4(), V.g, 1e-5f);
	auto grbb = V.grbb;
	BOOST_CHECK_CLOSE(grbb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(grbb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(grbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(grbb.getE4(), V.b, 1e-5f);
	auto ggrr = V.ggrr;
	BOOST_CHECK_CLOSE(ggrr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggrr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(ggrr.getE4(), V.r, 1e-5f);
	auto ggrg = V.ggrg;
	BOOST_CHECK_CLOSE(ggrg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggrg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(ggrg.getE4(), V.g, 1e-5f);
	auto ggrb = V.ggrb;
	BOOST_CHECK_CLOSE(ggrb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggrb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(ggrb.getE4(), V.b, 1e-5f);
	auto gggr = V.gggr;
	BOOST_CHECK_CLOSE(gggr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggr.getE4(), V.r, 1e-5f);
	auto gggg = V.gggg;
	BOOST_CHECK_CLOSE(gggg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggg.getE4(), V.g, 1e-5f);
	auto gggb = V.gggb;
	BOOST_CHECK_CLOSE(gggb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gggb.getE4(), V.b, 1e-5f);
	auto ggbr = V.ggbr;
	BOOST_CHECK_CLOSE(ggbr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggbr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(ggbr.getE4(), V.r, 1e-5f);
	auto ggbg = V.ggbg;
	BOOST_CHECK_CLOSE(ggbg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggbg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(ggbg.getE4(), V.g, 1e-5f);
	auto ggbb = V.ggbb;
	BOOST_CHECK_CLOSE(ggbb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggbb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(ggbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(ggbb.getE4(), V.b, 1e-5f);
	auto gbrr = V.gbrr;
	BOOST_CHECK_CLOSE(gbrr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbrr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(gbrr.getE4(), V.r, 1e-5f);
	auto gbrg = V.gbrg;
	BOOST_CHECK_CLOSE(gbrg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbrg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(gbrg.getE4(), V.g, 1e-5f);
	auto gbrb = V.gbrb;
	BOOST_CHECK_CLOSE(gbrb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbrb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(gbrb.getE4(), V.b, 1e-5f);
	auto gbgr = V.gbgr;
	BOOST_CHECK_CLOSE(gbgr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbgr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbgr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbgr.getE4(), V.r, 1e-5f);
	auto gbgg = V.gbgg;
	BOOST_CHECK_CLOSE(gbgg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbgg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbgg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbgg.getE4(), V.g, 1e-5f);
	auto gbgb = V.gbgb;
	BOOST_CHECK_CLOSE(gbgb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbgb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbgb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbgb.getE4(), V.b, 1e-5f);
	auto gbbr = V.gbbr;
	BOOST_CHECK_CLOSE(gbbr.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbbr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbbr.getE4(), V.r, 1e-5f);
	auto gbbg = V.gbbg;
	BOOST_CHECK_CLOSE(gbbg.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbbg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbbg.getE4(), V.g, 1e-5f);
	auto gbbb = V.gbbb;
	BOOST_CHECK_CLOSE(gbbb.getE1(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(gbbb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(gbbb.getE4(), V.b, 1e-5f);
	auto brrr = V.brrr;
	BOOST_CHECK_CLOSE(brrr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brrr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brrr.getE4(), V.r, 1e-5f);
	auto brrg = V.brrg;
	BOOST_CHECK_CLOSE(brrg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brrg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brrg.getE4(), V.g, 1e-5f);
	auto brrb = V.brrb;
	BOOST_CHECK_CLOSE(brrb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brrb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brrb.getE4(), V.b, 1e-5f);
	auto brgr = V.brgr;
	BOOST_CHECK_CLOSE(brgr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brgr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brgr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(brgr.getE4(), V.r, 1e-5f);
	auto brgg = V.brgg;
	BOOST_CHECK_CLOSE(brgg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brgg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brgg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(brgg.getE4(), V.g, 1e-5f);
	auto brgb = V.brgb;
	BOOST_CHECK_CLOSE(brgb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brgb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brgb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(brgb.getE4(), V.b, 1e-5f);
	auto brbr = V.brbr;
	BOOST_CHECK_CLOSE(brbr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brbr.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brbr.getE4(), V.r, 1e-5f);
	auto brbg = V.brbg;
	BOOST_CHECK_CLOSE(brbg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brbg.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brbg.getE4(), V.g, 1e-5f);
	auto brbb = V.brbb;
	BOOST_CHECK_CLOSE(brbb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brbb.getE2(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(brbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(brbb.getE4(), V.b, 1e-5f);
	auto bgrr = V.bgrr;
	BOOST_CHECK_CLOSE(bgrr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgrr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(bgrr.getE4(), V.r, 1e-5f);
	auto bgrg = V.bgrg;
	BOOST_CHECK_CLOSE(bgrg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgrg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(bgrg.getE4(), V.g, 1e-5f);
	auto bgrb = V.bgrb;
	BOOST_CHECK_CLOSE(bgrb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgrb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(bgrb.getE4(), V.b, 1e-5f);
	auto bggr = V.bggr;
	BOOST_CHECK_CLOSE(bggr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bggr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bggr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bggr.getE4(), V.r, 1e-5f);
	auto bggg = V.bggg;
	BOOST_CHECK_CLOSE(bggg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bggg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bggg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bggg.getE4(), V.g, 1e-5f);
	auto bggb = V.bggb;
	BOOST_CHECK_CLOSE(bggb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bggb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bggb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bggb.getE4(), V.b, 1e-5f);
	auto bgbr = V.bgbr;
	BOOST_CHECK_CLOSE(bgbr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgbr.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgbr.getE4(), V.r, 1e-5f);
	auto bgbg = V.bgbg;
	BOOST_CHECK_CLOSE(bgbg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgbg.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgbg.getE4(), V.g, 1e-5f);
	auto bgbb = V.bgbb;
	BOOST_CHECK_CLOSE(bgbb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgbb.getE2(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bgbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bgbb.getE4(), V.b, 1e-5f);
	auto bbrr = V.bbrr;
	BOOST_CHECK_CLOSE(bbrr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbrr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbrr.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(bbrr.getE4(), V.r, 1e-5f);
	auto bbrg = V.bbrg;
	BOOST_CHECK_CLOSE(bbrg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbrg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbrg.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(bbrg.getE4(), V.g, 1e-5f);
	auto bbrb = V.bbrb;
	BOOST_CHECK_CLOSE(bbrb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbrb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbrb.getE3(), V.r, 1e-5f);
	BOOST_CHECK_CLOSE(bbrb.getE4(), V.b, 1e-5f);
	auto bbgr = V.bbgr;
	BOOST_CHECK_CLOSE(bbgr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbgr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbgr.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bbgr.getE4(), V.r, 1e-5f);
	auto bbgg = V.bbgg;
	BOOST_CHECK_CLOSE(bbgg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbgg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbgg.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bbgg.getE4(), V.g, 1e-5f);
	auto bbgb = V.bbgb;
	BOOST_CHECK_CLOSE(bbgb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbgb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbgb.getE3(), V.g, 1e-5f);
	BOOST_CHECK_CLOSE(bbgb.getE4(), V.b, 1e-5f);
	auto bbbr = V.bbbr;
	BOOST_CHECK_CLOSE(bbbr.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbr.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbr.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbr.getE4(), V.r, 1e-5f);
	auto bbbg = V.bbbg;
	BOOST_CHECK_CLOSE(bbbg.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbg.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbg.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbg.getE4(), V.g, 1e-5f);
	auto bbbb = V.bbbb;
	BOOST_CHECK_CLOSE(bbbb.getE1(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbb.getE2(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbb.getE3(), V.b, 1e-5f);
	BOOST_CHECK_CLOSE(bbbb.getE4(), V.b, 1e-5f);
	// 4d swizzles <s, t, p>
	auto ssss = V.ssss;
	BOOST_CHECK_CLOSE(ssss.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssss.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssss.getE4(), V.s, 1e-5f);
	auto ssst = V.ssst;
	BOOST_CHECK_CLOSE(ssst.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssst.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssst.getE4(), V.t, 1e-5f);
	auto sssp = V.sssp;
	BOOST_CHECK_CLOSE(sssp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sssp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sssp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sssp.getE4(), V.p, 1e-5f);
	auto ssts = V.ssts;
	BOOST_CHECK_CLOSE(ssts.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssts.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ssts.getE4(), V.s, 1e-5f);
	auto sstt = V.sstt;
	BOOST_CHECK_CLOSE(sstt.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sstt.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sstt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sstt.getE4(), V.t, 1e-5f);
	auto sstp = V.sstp;
	BOOST_CHECK_CLOSE(sstp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sstp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sstp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sstp.getE4(), V.p, 1e-5f);
	auto ssps = V.ssps;
	BOOST_CHECK_CLOSE(ssps.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssps.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ssps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ssps.getE4(), V.s, 1e-5f);
	auto sspt = V.sspt;
	BOOST_CHECK_CLOSE(sspt.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sspt.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sspt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sspt.getE4(), V.t, 1e-5f);
	auto sspp = V.sspp;
	BOOST_CHECK_CLOSE(sspp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sspp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sspp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sspp.getE4(), V.p, 1e-5f);
	auto stss = V.stss;
	BOOST_CHECK_CLOSE(stss.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stss.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stss.getE4(), V.s, 1e-5f);
	auto stst = V.stst;
	BOOST_CHECK_CLOSE(stst.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stst.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stst.getE4(), V.t, 1e-5f);
	auto stsp = V.stsp;
	BOOST_CHECK_CLOSE(stsp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stsp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stsp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stsp.getE4(), V.p, 1e-5f);
	auto stts = V.stts;
	BOOST_CHECK_CLOSE(stts.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stts.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stts.getE4(), V.s, 1e-5f);
	auto sttt = V.sttt;
	BOOST_CHECK_CLOSE(sttt.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sttt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sttt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sttt.getE4(), V.t, 1e-5f);
	auto sttp = V.sttp;
	BOOST_CHECK_CLOSE(sttp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sttp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sttp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sttp.getE4(), V.p, 1e-5f);
	auto stps = V.stps;
	BOOST_CHECK_CLOSE(stps.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stps.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(stps.getE4(), V.s, 1e-5f);
	auto stpt = V.stpt;
	BOOST_CHECK_CLOSE(stpt.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stpt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stpt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(stpt.getE4(), V.t, 1e-5f);
	auto stpp = V.stpp;
	BOOST_CHECK_CLOSE(stpp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(stpp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(stpp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(stpp.getE4(), V.p, 1e-5f);
	auto spss = V.spss;
	BOOST_CHECK_CLOSE(spss.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spss.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(spss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spss.getE4(), V.s, 1e-5f);
	auto spst = V.spst;
	BOOST_CHECK_CLOSE(spst.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spst.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(spst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spst.getE4(), V.t, 1e-5f);
	auto spsp = V.spsp;
	BOOST_CHECK_CLOSE(spsp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spsp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(spsp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spsp.getE4(), V.p, 1e-5f);
	auto spts = V.spts;
	BOOST_CHECK_CLOSE(spts.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spts.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(spts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(spts.getE4(), V.s, 1e-5f);
	auto sptt = V.sptt;
	BOOST_CHECK_CLOSE(sptt.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sptt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sptt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sptt.getE4(), V.t, 1e-5f);
	auto sptp = V.sptp;
	BOOST_CHECK_CLOSE(sptp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sptp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sptp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(sptp.getE4(), V.p, 1e-5f);
	auto spps = V.spps;
	BOOST_CHECK_CLOSE(spps.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(spps.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(spps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(spps.getE4(), V.s, 1e-5f);
	auto sppt = V.sppt;
	BOOST_CHECK_CLOSE(sppt.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sppt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sppt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sppt.getE4(), V.t, 1e-5f);
	auto sppp = V.sppp;
	BOOST_CHECK_CLOSE(sppp.getE1(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(sppp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sppp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(sppp.getE4(), V.p, 1e-5f);
	auto tsss = V.tsss;
	BOOST_CHECK_CLOSE(tsss.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tsss.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tsss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tsss.getE4(), V.s, 1e-5f);
	auto tsst = V.tsst;
	BOOST_CHECK_CLOSE(tsst.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tsst.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tsst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tsst.getE4(), V.t, 1e-5f);
	auto tssp = V.tssp;
	BOOST_CHECK_CLOSE(tssp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tssp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tssp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tssp.getE4(), V.p, 1e-5f);
	auto tsts = V.tsts;
	BOOST_CHECK_CLOSE(tsts.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tsts.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tsts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tsts.getE4(), V.s, 1e-5f);
	auto tstt = V.tstt;
	BOOST_CHECK_CLOSE(tstt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tstt.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tstt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tstt.getE4(), V.t, 1e-5f);
	auto tstp = V.tstp;
	BOOST_CHECK_CLOSE(tstp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tstp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tstp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tstp.getE4(), V.p, 1e-5f);
	auto tsps = V.tsps;
	BOOST_CHECK_CLOSE(tsps.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tsps.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tsps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tsps.getE4(), V.s, 1e-5f);
	auto tspt = V.tspt;
	BOOST_CHECK_CLOSE(tspt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tspt.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tspt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tspt.getE4(), V.t, 1e-5f);
	auto tspp = V.tspp;
	BOOST_CHECK_CLOSE(tspp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tspp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tspp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tspp.getE4(), V.p, 1e-5f);
	auto ttss = V.ttss;
	BOOST_CHECK_CLOSE(ttss.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttss.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ttss.getE4(), V.s, 1e-5f);
	auto ttst = V.ttst;
	BOOST_CHECK_CLOSE(ttst.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttst.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ttst.getE4(), V.t, 1e-5f);
	auto ttsp = V.ttsp;
	BOOST_CHECK_CLOSE(ttsp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttsp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttsp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ttsp.getE4(), V.p, 1e-5f);
	auto ttts = V.ttts;
	BOOST_CHECK_CLOSE(ttts.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttts.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttts.getE4(), V.s, 1e-5f);
	auto tttt = V.tttt;
	BOOST_CHECK_CLOSE(tttt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tttt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tttt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tttt.getE4(), V.t, 1e-5f);
	auto tttp = V.tttp;
	BOOST_CHECK_CLOSE(tttp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tttp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tttp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tttp.getE4(), V.p, 1e-5f);
	auto ttps = V.ttps;
	BOOST_CHECK_CLOSE(ttps.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttps.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ttps.getE4(), V.s, 1e-5f);
	auto ttpt = V.ttpt;
	BOOST_CHECK_CLOSE(ttpt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttpt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttpt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ttpt.getE4(), V.t, 1e-5f);
	auto ttpp = V.ttpp;
	BOOST_CHECK_CLOSE(ttpp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttpp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ttpp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ttpp.getE4(), V.p, 1e-5f);
	auto tpss = V.tpss;
	BOOST_CHECK_CLOSE(tpss.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tpss.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tpss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tpss.getE4(), V.s, 1e-5f);
	auto tpst = V.tpst;
	BOOST_CHECK_CLOSE(tpst.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tpst.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tpst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tpst.getE4(), V.t, 1e-5f);
	auto tpsp = V.tpsp;
	BOOST_CHECK_CLOSE(tpsp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tpsp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tpsp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(tpsp.getE4(), V.p, 1e-5f);
	auto tpts = V.tpts;
	BOOST_CHECK_CLOSE(tpts.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tpts.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tpts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tpts.getE4(), V.s, 1e-5f);
	auto tptt = V.tptt;
	BOOST_CHECK_CLOSE(tptt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tptt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tptt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tptt.getE4(), V.t, 1e-5f);
	auto tptp = V.tptp;
	BOOST_CHECK_CLOSE(tptp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tptp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tptp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tptp.getE4(), V.p, 1e-5f);
	auto tpps = V.tpps;
	BOOST_CHECK_CLOSE(tpps.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tpps.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tpps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tpps.getE4(), V.s, 1e-5f);
	auto tppt = V.tppt;
	BOOST_CHECK_CLOSE(tppt.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tppt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tppt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tppt.getE4(), V.t, 1e-5f);
	auto tppp = V.tppp;
	BOOST_CHECK_CLOSE(tppp.getE1(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(tppp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tppp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(tppp.getE4(), V.p, 1e-5f);
	auto psss = V.psss;
	BOOST_CHECK_CLOSE(psss.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(psss.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(psss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(psss.getE4(), V.s, 1e-5f);
	auto psst = V.psst;
	BOOST_CHECK_CLOSE(psst.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(psst.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(psst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(psst.getE4(), V.t, 1e-5f);
	auto pssp = V.pssp;
	BOOST_CHECK_CLOSE(pssp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pssp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(pssp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(pssp.getE4(), V.p, 1e-5f);
	auto psts = V.psts;
	BOOST_CHECK_CLOSE(psts.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(psts.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(psts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(psts.getE4(), V.s, 1e-5f);
	auto pstt = V.pstt;
	BOOST_CHECK_CLOSE(pstt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pstt.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(pstt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pstt.getE4(), V.t, 1e-5f);
	auto pstp = V.pstp;
	BOOST_CHECK_CLOSE(pstp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pstp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(pstp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pstp.getE4(), V.p, 1e-5f);
	auto psps = V.psps;
	BOOST_CHECK_CLOSE(psps.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(psps.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(psps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(psps.getE4(), V.s, 1e-5f);
	auto pspt = V.pspt;
	BOOST_CHECK_CLOSE(pspt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pspt.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(pspt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pspt.getE4(), V.t, 1e-5f);
	auto pspp = V.pspp;
	BOOST_CHECK_CLOSE(pspp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pspp.getE2(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(pspp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pspp.getE4(), V.p, 1e-5f);
	auto ptss = V.ptss;
	BOOST_CHECK_CLOSE(ptss.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptss.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ptss.getE4(), V.s, 1e-5f);
	auto ptst = V.ptst;
	BOOST_CHECK_CLOSE(ptst.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptst.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ptst.getE4(), V.t, 1e-5f);
	auto ptsp = V.ptsp;
	BOOST_CHECK_CLOSE(ptsp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptsp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptsp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ptsp.getE4(), V.p, 1e-5f);
	auto ptts = V.ptts;
	BOOST_CHECK_CLOSE(ptts.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptts.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptts.getE4(), V.s, 1e-5f);
	auto pttt = V.pttt;
	BOOST_CHECK_CLOSE(pttt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pttt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pttt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pttt.getE4(), V.t, 1e-5f);
	auto pttp = V.pttp;
	BOOST_CHECK_CLOSE(pttp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pttp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pttp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pttp.getE4(), V.p, 1e-5f);
	auto ptps = V.ptps;
	BOOST_CHECK_CLOSE(ptps.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptps.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptps.getE4(), V.s, 1e-5f);
	auto ptpt = V.ptpt;
	BOOST_CHECK_CLOSE(ptpt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptpt.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptpt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptpt.getE4(), V.t, 1e-5f);
	auto ptpp = V.ptpp;
	BOOST_CHECK_CLOSE(ptpp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptpp.getE2(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ptpp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ptpp.getE4(), V.p, 1e-5f);
	auto ppss = V.ppss;
	BOOST_CHECK_CLOSE(ppss.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppss.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppss.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ppss.getE4(), V.s, 1e-5f);
	auto ppst = V.ppst;
	BOOST_CHECK_CLOSE(ppst.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppst.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppst.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ppst.getE4(), V.t, 1e-5f);
	auto ppsp = V.ppsp;
	BOOST_CHECK_CLOSE(ppsp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppsp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppsp.getE3(), V.s, 1e-5f);
	BOOST_CHECK_CLOSE(ppsp.getE4(), V.p, 1e-5f);
	auto ppts = V.ppts;
	BOOST_CHECK_CLOSE(ppts.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppts.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppts.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(ppts.getE4(), V.s, 1e-5f);
	auto pptt = V.pptt;
	BOOST_CHECK_CLOSE(pptt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pptt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pptt.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pptt.getE4(), V.t, 1e-5f);
	auto pptp = V.pptp;
	BOOST_CHECK_CLOSE(pptp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pptp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pptp.getE3(), V.t, 1e-5f);
	BOOST_CHECK_CLOSE(pptp.getE4(), V.p, 1e-5f);
	auto ppps = V.ppps;
	BOOST_CHECK_CLOSE(ppps.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppps.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppps.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(ppps.getE4(), V.s, 1e-5f);
	auto pppt = V.pppt;
	BOOST_CHECK_CLOSE(pppt.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pppt.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pppt.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pppt.getE4(), V.t, 1e-5f);
	auto pppp = V.pppp;
	BOOST_CHECK_CLOSE(pppp.getE1(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pppp.getE2(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pppp.getE3(), V.p, 1e-5f);
	BOOST_CHECK_CLOSE(pppp.getE4(), V.p, 1e-5f);
}

BOOST_AUTO_TEST_CASE(swizzle_assign) {
	math::Vector3 V;
	V.x = 20.12f;
	V.y = 100.89f;
	V.z = -18.2f;
	math::Vector3 V_fromSwizzle;
	V_fromSwizzle.x = 9999.0f;
	V_fromSwizzle.y = 9999.0f;
	V_fromSwizzle.z = 9999.0f;
	// assign in-order from vector
	V_fromSwizzle.xyz = V;
	BOOST_CHECK_CLOSE(V.x, V_fromSwizzle.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.y, V_fromSwizzle.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V_fromSwizzle.z, 1e-5f);
	// assign out-of-order from vector
	V_fromSwizzle.yxz = V;
	BOOST_CHECK_CLOSE(V.y, V_fromSwizzle.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.x, V_fromSwizzle.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V_fromSwizzle.z, 1e-5f);
	// assign in-order from swizzle
	V_fromSwizzle.xyz = V.xxx;
	BOOST_CHECK_CLOSE(V.x, V_fromSwizzle.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.x, V_fromSwizzle.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.x, V_fromSwizzle.z, 1e-5f);
	// assign out-of-order from swizzle
	V_fromSwizzle.yzx = V.xzy;
	BOOST_CHECK_CLOSE(V.y, V_fromSwizzle.x, 1e-5f);
	BOOST_CHECK_CLOSE(V.x, V_fromSwizzle.y, 1e-5f);
	BOOST_CHECK_CLOSE(V.z, V_fromSwizzle.z, 1e-5f);
}

BOOST_AUTO_TEST_SUITE_END()
